### ISSUE TITLE
Test output is showing color codes

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#107]
**Describe the bug**

When using the `nvim-dap` integration to test, the output in the DAP-REPL shows the color codes. There is currently no way to turn this off when using using Bloop, and the same happens when using sbt.

**To Reproduce** Steps to reproduce the behavior:

1. Integrate with nvim-dap
2. Run a test
3. Look at the output in the DAP-REPL
4. See the following

## With Bloop

<img width="637" alt="Screenshot 2021-03-11 at 15 02 48" src="https://user-images.githubusercontent.com/13974112/110799302-50049d00-827b-11eb-9701-a2b4846d7366.png">

## With sbt

<img width="637" alt="Screenshot 2021-03-11 at 15 05 07" src="https://user-images.githubusercontent.com/13974112/110799324-5561e780-827b-11eb-82fc-f2d79d6f3789.png">

**Expected behavior**

There should be a way to turn color off

**Additional context**

- There is an upstream ticket for this in Bloop: https://github.com/scalacenter/bloop/issues/1478
- [x] I need to check to see if there is a way to turn this off when using sbt BSP

**Search terms**

DAP output

**Comment by adpi2** [comment]
For DAP in sbt there is a `isAnsiCodeSupported` that is set to true by default (for no good reason).

https://github.com/scalacenter/scala-debug-adapter/blob/5842b64cfcc6f4648226918c6d7beeeabb92c6fd/sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/SbtDebuggeeRunner.scala#L75

It could as well be false by default :)

**Comment by adpi2** [comment]
I have the same problem with BSP on the Scala 3 compiler logs. I need to dig more, but I think those color codes are coming from the Scala 3 compiler itself.

https://github.com/lampepfl/dotty/blob/e08fd59217265fa76d50eccd5c9594d94a89e0f8/sbt-bridge/src/dotty/tools/xsbt/DelegatingReporter.java#L37-L41

**Comment by ckipp01** [comment]
> For DAP in sbt there is a `isAnsiCodeSupported` that is set to true by default (for no good reason).
> 
> [scalacenter/scala-debug-adapter@`5842b64`/sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/SbtDebuggeeRunner.scala#L75](https://github.com/scalacenter/scala-debug-adapter/blob/5842b64cfcc6f4648226918c6d7beeeabb92c6fd/sbt/plugin/src/main/scala/ch/epfl/scala/debugadapter/sbtplugin/internal/SbtDebuggeeRunner.scala#L75)
> 
> It could as well be false by default :)

Aaha, thanks for pointing that out! Probably having it true by default is fine. The majority of the users will probably want that anyway. I think I'm the outlier here 😄. 

I'll try to dig into it a bit and see if there is a good way for a user to easily do this for this use case. We have the same issue with Bloop, so @tgodzik even suggested we just add the functionality to Metals to strip it.
