### ISSUE TITLE
Add a way to just update to the latest snapshot without having to manually set it.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#122]
**Describe the feature**

Basically I want to be able to just set `metals_server_version` to `latest.snapshot` and call `:MetalsInstall` at any time and get the latest snapshot installed. Part of the issue for this is that I can't figure out a way with Coursier to _actually_ get the latest snapshot from sontaypt:snapshots. We even do a super hacky thing in Metals where we query the html page and grab the latest release that way to display in the docs.

**Potential ways to implement?**

Ideally just with a Coursier call to get the latest.

**Additional context**

Targeting `-r sonatype:snapshots` with Coursier to get the latest via complete doesn't works as I'd expect. It just gives you the stable releases.

**Search terms**

latest snapshot

**Comment by keynmol** [comment]
I had interest in this as well (additionally, making it work with scala3 nightlies) so I did some investigating on the coursier issue: https://github.com/coursier/coursier/issues/1700#issuecomment-912498601

**Comment by ayoub-benali** [comment]
I am also interested in adding that to https://github.com/scalameta/metals-sublime
