### ISSUE TITLE
Allow passing in of arguments when running sbt tasks

### ISSUE THREAD

**Issue by jsatk** [scalameta/nvim-metals#129]
**Is your feature request related to a problem? Please describe.**

When using Metals (via nvim-metals plugin) + [DAP](https://github.com/dradtke/vim-dap) is there a way to provide arguments to methods when you're choosing which to run? When I tell it to `Run` it shows a prompt asking me to select the job and it just runs. Not sure how to pass arguments to it 🤔 It's unclear to me where DAP ends and Metals begins here though. So please feel free to close this or correct me if I'm wrong about something.

**Describe the solution you'd like**
When I am prompted on which job/task to run and I select it there could be a following prompt where I can optionally pass it args. I think a simple list of space separated arguments is fine just like how sbt does. I.E. In sbt if I'd run `sbt foo "arg1" "arg2" arg3" then the screen asking me for args would accept empty for no args or also just literally "arg1" "arg2" "arg3" for a series of string arguments.

**Describe alternatives you've considered**
There could optionally also be some sort of config file where you can specify the args for each job there. This would like be some .gitingore-ed file for most people. I don't love this nearly as much but might be a nice alternative if you're running the same task with the same args over and over. Although pressing up arrow should likely show you your previously used args in my initial solutions.

**Additional context**
None that I can think of.

**Search terms**:
DAP args arguments job task run debugger vim nvim

**Comment by ckipp01** [comment]
I moved this over here @jsatk since there is ways to do this in Metals in general and in the other editors, but it's not flushed out for nvim-metals. I'll work on figuring out the best way to offer this here and document it.

**Comment by jsatk** [comment]
I didn't even know you _could_ transfer issues. Amazing.
