### ISSUE TITLE
nvim-metals process does not exit on nvim exit

### ISSUE THREAD

**Issue by mpasa** [scalameta/nvim-metals#139]
**Describe the bug**

nvim-metals creates a process when opening a Scala project, and it looks like it's not killed when nvim exits.

**To Reproduce** Steps to reproduce the behavior:

1. Open nvim in a Scala project.
2. Open any Scala file, which will trigger the start of the LSP.
    ```
    λ ps aux | grep nvim-metals
    miguel    861031 62.8  6.3 10007316 1029756 pts/4 Sl  12:59   0:56 /home/miguel/.asdf/installs/java/adoptopenjdk-8.0.282+8/bin/java -Xss4m -Xms100m -jar /home/miguel/.cache/nvim/nvim-metals/metals
    ```
3. Exit vim with `:q`. You can execute again the previous command to see the same process is still around.
4. Open the project again, and then a Scala file.
5. Check that there are now 2 nvim-metals processes.
    ```
    λ ps aux | grep nvim-metals
    miguel    861031 14.5  6.3 10003216 1029736 pts/4 Sl  12:59   0:56 /home/miguel/.asdf/installs/java/adoptopenjdk-8.0.282+8/bin/java -Xss4m -Xms100m -jar /home/miguel/.cache/nvim/nvim-metals/metals
    miguel    864326 22.7  6.3 10003216 1025104 pts/4 Sl  13:02   0:45 /home/miguel/.asdf/installs/java/adoptopenjdk-8.0.282+8/bin/java -Xss4m -Xms100m -jar /home/miguel/.cache/nvim/nvim-metals/metals
    ```
6. Exit nvim again with `:q` and check how the processes are still running.

**Expected behavior**

The metals process is killed when nvim exits, or it's re-used between instances.

**Installation:**

- Operating system: Linux
- Nvim version: v0.5.0-dev+1274-gbb3372792
- Commit of nvim-metals: 69a5cf9380defde5be675bd5450e087d59314855
- Metals version: 0.10.2

**Search terms**

process, exit

**Comment by ckipp01** [comment]
Thanks for the report @mpasa. I'm not really sure what's going on here. I can't reproduce locally, but there are a couple things we can check to try to pin point what might be going on. I've listed some steps below that will help:

1.  Firstly, can you create a `~/.cache/metals/lsp.trace.json` file. This will be a log of all of the lsp communication between nvim-metals and metals.
2. Tail the above file and also the `.metals/metals.log` file in your workspace as you open up, wait for indexing to finish, and then do a `:q`.
3. Copy in here the final things you see in your `lsp.trace.json` file and your `metals.log` file. I'd expect something like the following:

metals.log
```
2021.05.13 14:51:32 INFO  shutting down Metals
No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
2021.05.13 14:51:32 No more data in the server stdin, exiting...INFO
 No more data in the server stdin, exiting...Shut down connection with build server.
No more data in the server stdin, exiting...

No more data in the server stdin, exiting...
2021.05.13 14:51:32 INFO  Shut down connection with build server.
2021.05.13 14:51:32 INFO  No more data in the client stdin, exiting...Shut down connection with build server.

No more data in the client stdin, exiting...
No more data in the client stdin, exiting...
```

and in the trace file:
```
[Trace - 02:51:32 PM] Received request 'shutdown - (2)'
Params: null


[Trace - 02:51:32 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 14:51:32 INFO  shutting down Metals"
}


[Trace - 02:51:32 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 14:51:32 INFO  Shut down connection with build server."
}


[Trace - 02:51:32 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 14:51:32 INFO  Shut down connection with build server."
}


[Trace - 02:51:32 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 14:51:32 INFO  Shut down connection with build server."
}


[Trace - 02:51:32 PM] Sending response 'shutdown - (2)'. Processing request took 17ms
Result: {}


[Trace - 02:51:32 PM] Received notification 'exit'
Params: null
```

We'll check if you are seeing the same thing to maybe see if something is affecting the shutdown request.

**Comment by mpasa** [comment]
Everything looks kind of normal. I'm just missing the last 2 lines of the trace log.

metals.log

```
2021.05.13 18:50:46 INFO  shutting down Metals
2021.05.13 18:50:46 INFO  Shut down connection with build server.
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
2021.05.13 18:50:46 INFO  Shut down connection with build server.No more data in the server stdin, exiting...
No more data in the server stdin, exiting...

No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
No more data in the client stdin, exiting...
2021.05.13 18:50:46 INFO  Shut down connection with build server.
No more data in the client stdin, exiting...
```

trace file:

```
[Trace - 06:50:46 PM] Received request 'shutdown - (10)'
Params: null


[Trace - 06:50:46 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 18:50:46 INFO  shutting down Metals" Y
}


[Trace - 06:50:46 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 18:50:46 INFO  Shut down connection with build server."
}


[Trace - 06:50:46 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 18:50:46 INFO  Shut down connection with build server."
}


[Trace - 06:50:46 PM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.13 18:50:46 INFO  Shut down connection with build server."
}


[Trace - 06:50:46 PM] Sending response 'shutdown - (10)'. Processing request took 91ms
Result: {}
```

**Comment by mpasa** [comment]
Some updates. I tried tracing the signals sent to the defined `config.cmd` process.

```
λ sudo strace -p 282207 -e 'trace=!all'
strace: Process 282207 attached
```

There are no signals sent to it, until I send a SIGTERM manually using `kill <pid>`.

I have also tried to stop the server manually, without nvim sending the signal:

```lua
config.on_exit = function(code, signal, client_id)
  print("Exited metals server. Exit code: " .. code .. ". Signal: " .. signal)
end

local client_id = lsps[config.root_dir]
if not client_id then
  client_id = lsp.start_client(config)
  lsps[config.root_dir] = client_id
end
lsp.buf_attach_client(bufnr, client_id)

lsp.stop_client(client_id)
```

- I added the `on_exit` listener to print a message when we receive the exit code from the server.
- I added a manual stop after starting the server and attaching it to the buffer.

The result is:

```
Exited metals server. Exit code: 0. Signal: 15
```

In this case, the metals server is killed correctly using a SIGTERM. So, it looks like my nvim is
being killed prematurely before the exit signal is sent to the server.

Next thing I can do is check a trace log from nvim with `nvim -V15log.log`. On the log, I see

```
Executing VimLeavePre Autocommands for "*"
autocommand lua vim.lsp._vim_exit_handler()

Executing: lua vim.lsp._vim_exit_handler()
```

This looks good, but I don't see much more. Let's modify the nvim runtime to see if I can get some more logs.

```lua
function lsp._vim_exit_handler()
  log.info("exit_handler", active_clients)
  dump(uninitialized_clients)
  for _, client in pairs(uninitialized_clients) do
    client.stop(true)
  end
  dump(active_clients)
  -- TODO handle v:dying differently?
  if tbl_isempty(active_clients) then
    return
  end
  for _, client in pairs(active_clients) do
    client.stop()
  end

  ...
}
```

`dump` is a function I have to dump tables. If indexing was complete, metals appears correctly in the `active_clients` table, and the correct pid is tracked:

```lua
['rpc'] = {
  ['notify'] = 'function: 0x7fe131c97d88',
  ['handle'] = 'uv_process_t: 0x02bd9790',
  ['request'] = 'function: 0x7fe131f86468',
  ['pid'] = 354822
}
```

It first tries to stop the server in a graceful way. If it's not closed, it tries to force close it
for some time. It looks like it doesn't get to the waiting part, so I will check the implementation
of `function client.stop(force)`.

Here, it seems the `rpc.request('shutdown', nil, function(err, _)` function is called, but we never
get to execute the callback. For that reason, this part is not executed:

```lua
if err == nil then
  rpc.notify('exit')
else
  -- If there was an error in the shutdown request, then term to be safe.
  handle:kill(15)
end
```

At this point, I don't know how to continue debugging, but it looks it's something with my Metals or
nvim versions, as it looks the server is not answering to that RPC call. I tried to run again
`MetalsInstall`, and to remove `.metals` directory. The result is still the same.

**Comment by ckipp01** [comment]
Ah you really did a deep dive! 🙏🏼 this is super helpful. I'm on holiday for a week, but when I get back I'll try to dive deep into this as well to see if I can maybe figure out what's happening.

**Comment by mpasa** [comment]
I updated my nightly nvim version and it looks it's fixed. Now I receive the exit notification and the process is killed, both if the indexing was complete or if it was not.

```
Params: {
  "type": 4,
  "message": "2021.05.23 08:47:31 INFO  Shut down connection with build server."
}


[Trace - 08:47:31 AM] Sending response 'shutdown - (4)'. Processing request took 67ms
Result: {}


[Trace - 08:47:31 AM] Received notification 'exit'
Params: null[Trace - 08:47:31 AM] Sending notification 'window/logMessage'
Params: {
  "type": 4,
  "message": "2021.05.23 08:47:31 INFO  Shut down connection with build server."
}


[Trace - 08:47:31 AM] Sending response 'shutdown - (4)'. Processing request took 67ms
Result: {}


[Trace - 08:47:31 AM] Received notification 'exit'
Params: null
```

The current nvim version is **NVIM v0.5.0-dev+1345-g6dd04ed5f**. I'm closing as it was not related to the plugin. Thank you very much.

**Comment by ckipp01** [comment]
Hey! I'm really glad that updating fixed this, but it's still odd to me it was happening in the first place. If this pops up again, don't hesitate to re-open.
