### ISSUE TITLE
New Scala File creating at times in wrong folder

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#163]
**Describe the bug**

I haven't fully reproduced this yet, but it's been happening enough for me to report it, and then I'll try to figure it out.

**To Reproduce** Steps to reproduce the behavior:

1. Navigate around a bit
2. Execute the `New Scala File` command
3. Create a new object 
4. At times it seems to create the file in the old directory you navigated from

**Expected behavior**

Create it in your current directory

**Search terms**

new scala file

**Comment by ckipp01** [comment]
Actually looking a bit closer, this seems to be due to `did_focus` not always being called when you navigate _back_ to a file. This is also screwing up worksheets a bit fore me.

**Comment by ivanopagano** [comment]
I think I have similar issues on vs-code too, could they be related and due to a more general issue with Metals?

**Comment by ckipp01** [comment]
_Possibly_, but I just looked at what happens in Metals if no params are passed in, and it should take the parent of the last focused document as the dir that the file is created in. I can confirm at least in nvim-metals the issue that I'm currently having is that if I'm in `A` and want to jump back to `B`, when I jump to `B` the `did_focus` function isn't being called.

https://github.com/scalameta/nvim-metals/blob/c681f53848c88b46d7107a2eab0cab9c83e37392/lua/metals/setup.lua#L324

So I'm trying to figure out why that's the case. This also then screws with worksheets where if you are in a worksheet, navigate out and then come back, it won't re-trigger an evaluation.
