### ISSUE TITLE
How to manage setup

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#17]
**Question**

As a follow-up to https://github.com/ckipp01/nvim-metals/pull/12#issuecomment-628661919, I think the setup needs to be addressed sooner rather than later.

Currently everything needs to be defined. For example, if you want to enable `metals/status`, then you need to do two things:
1. Set `statusBarProvider` to true in your `init_options`
2. Add a callback for `metals/status`

Then for every other thing that we are adding, we are having to do the same thing.

When I originally started this plugin I envisioned _not_ have a "do this one thing to get started" like there is in coc-metals, but rather instructions in how to tie everything together to hopefully utilize a bunch of other great plugins. However, I'm quickly realizing that we are going to end up creating quite a few callbacks, a lot of the `init_option` need to be set since the configuration in `nvim-lsp` is the very base just for Metals to work correctly for a user out of the box without `nvim-metals`. All that to say, I'm leaning more towards a simple way to add in `nvim-metals`, and have it do the necessary configuration without having a user add in 30 lines (apart from mappings of course). I think you also had a good point @landerlo about adding a new feature. Ideally a new feature can be added without the user having to adjust their setup.

**Approaches**

1. Just handle the entire installation of Metals, bootstrapping etc. This would rid the need of `nvim-lsp` at all. However, this would be the most work, and I'm not sure I want this. Just adding it here as an approach
2. > `Maybe instead of having to using the lua << whole setup code, have something like setup_nvim_metals { myOverrides }
3. Something completely different?

**Search terms**

setup

**Comment by mfussenegger** [comment]
For nvim-jdtls I ended up going with 1), although I initially was also opposed to doing that.

You can have a look at the change [here](https://github.com/mfussenegger/nvim-jdtls/commit/bc1e54f819ae892dacc2e36b0bfb0820c512a070#diff-e3d38c2c66d1904c53b644b11d0bf5c6R39) 

In the end it wasn't as much logic as I had thought.

**Comment by ckipp01** [comment]
Thanks for linking that @mfussenegger! That's really helpful. That's also the route I'm planning on taking as well now when I get some time.
