### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by ironfish** [scalameta/nvim-metals#190]
**Describe the bug**

I just started receiving this error on build import:
```
You are using Scala versions 2.12.14, 3.0.0, which are not yet supported in this version of Metals. Please downgrade to Scala versions 2.12.12, 3.0.0-M3 for the moment until the new Metals release.
```
**Installation:**
- Operating system: macOS
- Nvim version: v0.6.0-dev+13-ga6cdfa27d
- Commit of nvim-metals: af357ef
- Metals version: 0.10.4+146-b5f79053-SNAPSHOT

**Comment by ckipp01** [comment]
Hey @ironfish you are on an old version of Metals. Since you're using a snapshot, you can either update that to the latest [here](https://scalameta.org/metals/docs#latest-metals-server-versions), or just remove the current snapshot that you have set and just do a `:MetalsUpdate` to update to `0.10.5`.

**Comment by ironfish** [comment]
Okay @ckipp01, thanks for letting me know. It now seems to work.

**Comment by ironfish** [comment]
Hey @ckipp01, hate to reopen this issue, but i keep getting the same problem with Metals 0.10.5 - `You are using Scala versions 2.12.14, 3.0.0, which are not yet supported in this version of Metals. Please downgrade to Scala versions 2.12.12, 3.0.0-M3 for the moment until the new Metals release.`

**Comment by ironfish** [comment]
Here is my metals configuration if that helps:
```
-- https://github.com/scalameta/nvim-metals

local cmd = vim.cmd
local f = require('settings.functions')
local g = vim.g
local map = f.map

require('lspsaga').init_lsp_saga({
  border_style = "single",
  code_action_keys = {
    quit = 'q',exec = '<CR>'
  },
  code_action_prompt = {
    enable = true,
    sign = true,
    sign_priority = 20,
    virtual_text = true 
  },
  finder_action_keys = {
    open = 'o',
    vsplit = 's',
    split = 'i',
    quit = 'q',
    scroll_down = '<C-f>',
    scroll_up = '<C-b>' -- quit can be a table
  },
  rename_action_keys = {
    quit = '<C-c>',exec = '<CR>'  -- quit can be a table
  },
  server_filetype_map = { 
    metals = { "sbt", "scala" } 
  }
})

g['metals_server_version'] = '0.10.4+146-b5f79053-SNAPSHOT'
-- g['metals_server_version'] = '0.9.8+43-e729533a-SNAPSHOT'
-- g['metals_server_version'] = '0.10.3+23-3512dbc6-SNAPSHOT'

cmd [[augroup lsp]]
cmd [[au!]]
cmd [[au FileType scala,sbt lua require("metals").initialize_or_attach(metals_config)]]
cmd [[augroup end]]

-- cmd [[augroup lsp]]
-- cmd [[autocmd!]]
-- cmd [[autocmd FileType scala setlocal omnifunc=v:lua.vim.lsp.omnifunc]]
-- cmd [[autocmd FileType scala,sbt lua require("metals").initialize_or_attach(metals_config)]]
-- cmd [[augroup end]]

-- cmd [[augroup NvimMetals]]
-- cmd [[autocmd!]]
-- cmd [[autocmd BufEnter <buffer> lua require'metals'.did_focus()]]
-- cmd [[autocmd CursorHold  <buffer> lua vim.lsp.buf.document_highlight()]]
-- cmd [[autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()]]
-- cmd [[augroup end]]
-- 
cmd([[command! Format lua vim.lsp.buf.formatting()]])

-- need for symbol highlights to work correctly
cmd [[hi! link LspReferenceText CursorColumn]]
cmd [[hi! link LspReferenceRead CursorColumn]]
cmd [[hi! link LspReferenceWrite CursorColumn]]

metals_config = require'metals'.bare_config

-- Example of settings
metals_config.settings = {
  showImplicitArguments = true,
  showInferredType = true,
  excludedPackages = {
    "akka.actor.typed.javadsl", 
    "com.github.swagger.akka.javadsl",
    "akka.stream.javadsl"
  }
}

metals_config.init_options.statusBarProvider = "on"

-- Example of how to ovewrite a handler
metals_config.handlers['textDocument/publishDiagnostics'] =
    vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {virtual_text = {prefix = ''}})

-- Example if you are including snippets
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
metals_config.capabilities = capabilities

map("n", "<leader>ca",  [[<cmd>lua require('lspsaga.codeaction').code_action()<CR>]])
map("v", "<leader>ca",  [[<cmd>lua require('lspsaga.codeaction').range_code_action()<CR>]])
map('n', '<leader>cc',  [[<cmd>lua require('lspsaga.diagnostic').show_cursor_diagnostics()<CR>]])
map('n', '<leader>cd',  [[<cmd>lua require('lspsaga.diagnostic').show_line_diagnostics()<CR>]])
map('n', '<leader>cf',  [[<cmd>lua require('lspsaga.provider').lsp_finder()<CR>]])
map("n", "<leader>cgd", [[<cmd>lua vim.lsp.buf.definition()<CR>]])
map("n", "<leader>cgi", [[<cmd>lua vim.lsp.buf.implementation()<CR>]])
map("n", "<leader>cgr", [[<cmd>lua vim.lsp.buf.references()<CR>]])
map("n", "<leader>ch",  [[<cmd>lua require('lspsaga.hover').render_hover_doc()<CR>]])
map("n", "<leader>cr",  [[<cmd>lua require('lspsaga.rename').rename()<CR>]])
map('n', "<leader>cp",  [[<cmd>lua require('lspsaga.provider').preview_definition()<CR>]])

local keys = {
  c = {
    name = '+code',
    a = 'code-action',
    c = 'cursor-diagnostics',
    d = 'line-diagnostics',
    h = 'hover,doc',
    p = 'preview-definition',
    r = 'rename',
    g = {
      name = '+goto',
      d = 'goto-definition',
      i = 'goto-implimentation',
      r = 'goto-references',
    },
  }
}

require('which-key').register(keys, { prefix = "<leader>" })

-- not sure about these yet

map("n", "]c", [[<cmd>lua require('lspsaga.diagnostic').lsp_jump_diagnostic_next()<CR>]])
map("n", "[c", [[<cmd>lua require('lspsaga.diagnostic').lsp_jump_diagnostic_prev()<CR>]])
map("n", "gds", [[<cmd>lua require('telescope.builtin').lsp_document_symbols()<CR>]])
map("n", "gws", [[<cmd>lua require('settings.telescope').lsp_workspace_symbols()<CR>]])
map("n", "<leader>ws", [[<cmd>lua require('metals').worksheet_hover()<CR>]])
map("n", "<leader>a", [[<cmd>lua RELOAD('metals').open_all_diagnostics()<CR>]])
map("n", "<leader>tt", [[<cmd>lua require('metals.tvp').toggle_tree_view()<CR>]])
-- map("n", "<leader>d", [[<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>]]) -- buffer diagnostics only
-- map("n", "<leader>ln", [[<cmd>lua vim.lsp.diagnostic.get_line_diagnostics()<CR>]])
-- map("n", "<leader>q", [[<cmd>lua RELOAD("metals").restart_server()<CR>]])
```

**Comment by ironfish** [comment]
okay I had to add `g['metals_server_version'] = '0.10.5'` in order to get it to work. It then asked me to update my bloop server, which I did and everything seems to work. Why did I have to set the metals version in config? I thought it would automatically pull the latest.

**Comment by ckipp01** [comment]
Hey @ironfish so I looked a bit closer and didn't realize that you're using a commit of `nvim-metals` from over a year ago. I _highly_ recommend getting the latest as pretty much everything has changed in the past year. The current version your own doesn't even have the functionality to install Metals, back then it was handled by `nvim-lspconfig`, and the `metals_server_version` was grabbed by it and used to install. Now `nvim-metals` full handles the installation. So once everything is updated should be able to remove that setting and instead just to do `:MetalsInstall`. This will grab the `latest.release` as you can see here:

https://github.com/scalameta/nvim-metals/blob/7a6f175183e7115a660db2b8f5a4287a2e9e67d0/lua/metals/setup.lua#L88

**Comment by ironfish** [comment]
@ckipp01 thanks for getting back to me so quickly. Can you let me know which lines int the my config are causing those problems? Should I just remove all the `lsp` stuff and use only the setting you mention in https://github.com/scalameta/nvim-metals/blob/main/doc/metals.txt?

**Comment by ckipp01** [comment]
Well it's hard to tell without knowing the fully context of your setup.

Are you able to confirm that you're on the latest `nvim-metals`? If so, then to test that everything is working the very most minimal setup is simply:

```
cmd([[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]])
```

Then after the install you should be able to do a `:MetalsInfo` to verify the correct version of Metals is installed. Also if you haven't already, take a look at the minimal example in here https://github.com/scalameta/nvim-metals/discussions/39.

**Comment by ironfish** [comment]
Thanks, I will go ahead and do this when I get back home tonight and let you know how it works out. Thanks again for your quick responses.

**Comment by ckipp01** [comment]
Just checking @ironfish were you able to get this worked out?

**Comment by ironfish** [comment]
Hey @ckipp01 was away on vacation. Will configure today and test.

**Comment by ironfish** [comment]
Hi @ckipp01, made the changes and everything seems to be working. Thanks for your help.

**Comment by ironfish** [comment]
Hi @ckipp01, I really hate reopening this issue, but using [Minimal Config)(https://github.com/scalameta/nvim-metals/discussions/39) as my configuration I still get the same error unless I explicitly set `g['metals_server_version'] = '0.10.5'`.

**Comment by ckipp01** [comment]
@ironfish it's really hard to debug unless I have your full setup. When you say using the Minimal config, is that your entire `init.lua`? Do you have other stuff? What about when you use 
```
cmd([[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]])
```
Without any config at all? I'm really confused how this could be happening since explicitly setting the `metals_server_version` should not be necessary at all. Are you 100% sure as well that you're on the latest commit of nvim-metals?
