### ISSUE TITLE
Opt-out of auto_commands

### ISSUE THREAD

**Issue by perrin4869** [scalameta/nvim-metals#195]
**Describe the feature**

Currently, `nvim-metals` will [setup autocmd](https://github.com/scalameta/nvim-metals/blob/474151a9120f0939dc71a40abf58ff86e17336a3/lua/metals/setup.lua#L201) by default. The problem is that generally, these auto commands will already exists in people's configs, leading to duplication. For example, following this [tutorial](https://alpha2phi.medium.com/neovim-lsp-enhanced-a3d313abee65), you would end up with double `autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()`, without noticing unless you inspect the `CursorHold` autocmds. It would be helpful to make these autocmds either opt-in, opt-out, or up to individual user configuration.

**Potential ways to implement?**

Add a setup flag to `metals.initialize_or_attach` or remove the autocmds entirely.

**Comment by ckipp01** [comment]
Thanks for brining this up @perrin4869! So when I first started nvim-metals it was early on when stuff was _just_ getting started, so I wasn't really expected a lot of people to have everything set up. Including the autocmds were basically a way to onboard people more quickly. Now that things have stabilized I'm assuming that more people _will_ have these setup themselves. I think I'd like to just go ahead and remove the non-metals specific ones if no one objects to this.

**Comment by perrin4869** [comment]
This would be my preferred approach too :)
Thanks!
