### ISSUE TITLE
`.jvmopts` are ignored and no `metals.serverProperties` setting exists

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#196]
**Describe the bug**

So in the other Metals extensions there is some logic to grab what's in the environment and to also grab what's in the `metals.serverProperties` setting and ensure that Metals starts with with. This doesn't work currently when using `nvim-metals` mainly due to the difference in how we bootstrap Metals.

In the VS Code extension and `coc-metals` we actually fetch the dependency (Metals) and then provide the full classpath to be called to start Metals on every initialization. This works quite well as you never have to do a "Metals Install" to bootstrap Metals if you have everything locally already. Plus, you can more dynamically set things like your java options.

However, this is a bit more work to set up. When I first started `nvim-metals` I chose the route to instead bootstrap Metals via Coursier. This is what both your `:MetalsInstall` and `:MetalsUpdate` commands do. They use the Coursier [bootstrap](https://get-coursier.io/docs/cli-bootstrap) command to create a launcher that can simply be called. One down side of this is that as far as I know, there is no dynamic way to pass in stuff to it. So if you have properties you'd like to pass in, this needs to happen at the bootstrap time. There currently is no way for a user to do this and probably isn't super clear to a user. There are a couple options here to remedy this:

1. Create the `metals.serverProperties` setting which would allow you to put some extras in like `Xmx4096m` which would get added during bootstrap. However, this will be the properties Metals has until you do another bootstrap.
2. Do the same thing as the other plugins, use coursier to fetch the full classpath, put the classpath together, and then give it as the cmd to start Metals.

I'm unsure how I'd like to proceed with this as #2 is quite a bit more work. Any input from users would be appreciated.

**Comment by Sciss** [comment]
Not sure, but I would find it important that the metals installation done/used by nvim-metals is really local to it, i.e. it should not interfere with stuff installed by users otherwise. It sounds like the cs bootstrap will install in the general userspace, but I might be wrong. Otherwise, can't you just pass things via `-D` system properties or environment variables to the metals process?

**Comment by ckipp01** [comment]
> Standard bootstraps, standalone bootstraps, and assemblies, with the default shell preamble, automatically pass their arguments starting with -J to Java, stripping the leading -J, like
> 
> ```
> $ cs bootstrap ammonite -o amm
> $ ./amm -J-Dfoo=bar
> ```

HOW DID I MISS THIS?! This is exactly what I need actually and I totally glossed over it in the docs. Thanks @Sciss! This should work without any major changes then, so I'll just utilize this.

> Not sure, but I would find it important that the metals installation done/used by nvim-metals is really local to it, i.e. it should not interfere with stuff installed by users otherwise.

Correct, when you do a `:MetalsInstall` or `:MetalsUpdate` it puts it in `$HOME/.cache/nvim/nvim-metals/metals`. There is ways to use a global executable (mainly used by Nix users), but that's not the default.
