### ISSUE TITLE
Duplicate popups

### ISSUE THREAD

**Issue by chuwy** [scalameta/nvim-metals#227]
**Describe the bug**

I see different _things_ from metals being duplicated, for example:

1. I use [goto-preview](https://github.com/rmagatti/goto-preview/) for show definition and I'm getting two windows opened every time I call it (screenshot 1)
2. At first I thought it's goto-preview problem, but then also noticed some more generic functionality, like autocompletion showing several items for completion (screenshot 2)
3. Same for diagnostics - I see two errors

**To Reproduce** Steps to reproduce the behavior:

I realise that below is probably not what's going to reproduce the issue for most people and any suggestions how I can debug it would be welcome.

1. Open a metals project
2. Go to any symbol
3. Type `.` to get autocompletion
4. See duplicates in autocompletion

What's more - I managed to do above steps on a project without getting duplicates at some point, but don't know what caused it.

**Expected behavior**

No duplication

**Screenshots**

<img width="1263" alt="Screenshot 2021-09-23 at 15 38 07" src="https://user-images.githubusercontent.com/681171/134509041-1406bb70-64b8-4f7e-8a9d-e3b0e0133fa0.png">

<img width="787" alt="Screenshot 2021-09-23 at 15 41 31" src="https://user-images.githubusercontent.com/681171/134509122-e99673c4-cee1-45bd-93e5-2f5ecffeb533.png">

**Installation:**

- Operating system: macOS Catalina
- Nvim version: v0.6.0-dev (early August 2021)
- Commit of nvim-metals: 015d242
- Metals version: 0.10.6

**Additional context**

Started to see this after massic NeoVim upgrade: I switched to Packer, upgraded Metals and all other LSP-related stuff, switched to nvim-cmp. Not sure what exactly started causing this, but would appreciate any tips for debugging.

Settings relevant to Metals:

```lua
metals_config                                = require'metals'.bare_config
metals_config.init_options.statusBarProvider = 'on'
vim.g.metals_server_version                  = '0.10.6'
vim.api.nvim_buf_set_option(0, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
require('lspconfig')['metals'].setup {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
vim.cmd([[
set shortmess-=F
set shortmess+=c
augroup lsp
  au!
  au FileType scala,sbt lua require('metals').initialize_or_attach(metals_config)
augroup end
]])
```

**Comment by chuwy** [comment]
Ok, perhaps I was too eager to submit the bugreport, it seems this new line, suggested by nvim-cmp is causing this problem:

```lua
require('lspconfig')['metals'].setup {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
```

When combined with:

```lua
require('metals').initialize_or_attach(metals_config)
```

**Comment by ckipp01** [comment]
> Ok, perhaps I was too eager to submit the bugreport, it seems this new line, suggested by nvim-cmp is causing this problem:
> 
> ```lua
> require('lspconfig')['metals'].setup {
>   capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
> }
> ```
> 
> When combined with:
> 
> ```lua
> require('metals').initialize_or_attach(metals_config)
> ```

Hey! Exactly, that's why I have warnings all over the place to make sure not to mix the lspconfig metals with this plugin. Essentially by having both you're literally starting up 2 different instances of Metals causing you to see double of everything. If you have any other issues, let me know!

**Comment by chuwy** [comment]
Thank you very much, @ckipp01!

Just one thing I'd like to confirm. Would this be a correct configuration then:

```lua
metals_config = require'metals'.bare_config
vim.api.nvim_buf_set_option(0, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
metals_config.capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

...
au FileType scala,sbt lua require('metals').initialize_or_attach(metals_config)
```

As I understand it right now nvim-cmp provides an additional set of "capabilities" and I want to use them (whatever they are).

The config works fine for me - I just have tiny FOMO, like there's something that can work better.

**Comment by ckipp01** [comment]
So from looking at the docs, it's really not clear actually. It looks like `update_capabilities` is actually part of nvim-lsp-cmp, so it's only relevant if you are using that (I assume you are). I think by just having what you have here and nothing else, I don't think that's doing anything. You can see the options here: https://github.com/hrsh7th/cmp-nvim-lsp/blob/246a41c55668d5f84afcd805ee73b6e419375ae0/lua/cmp_nvim_lsp/init.lua#L23-L44

You'll have to dig into the docs and see if those are what you want or not.

**Comment by chuwy** [comment]
Got it! Thanks again.
