### ISSUE TITLE
Hovering extension for trimmed decorations

### ISSUE THREAD

**Issue by landerlo** [scalameta/nvim-metals#24]
At the moment we publish trimmed decorations as virtual text. The full hoverMessage is discarded.
The enhancement would allow to show the full decoration in a hover popup.

 Nvim LSP has the functions to show the popup hovering markdown window but I am not sure if it supports the registering of the markdown popup.

decoration-nvim might be of inspiration, but it probably it's as simple as storing the hoverMessage per line when getting the decorations, then we would check whether the line has decoration.

I think the easier approach of having to call a function to check for the decoration and show it is preferable to automatic popup as there could be a lot of noise from big popups appearing when we traverse lines.

The option of popup after staying in a line for some delay could be a nice option, though it's better to have it in a separate issue on its own, so we have a decoupled staying long in line callback that can trigger these other behaviours.

**Comment by ckipp01** [comment]
So my initial thought is to do something similar to what I did in coc-metals where the use can just execute a `<leader>ws` for example which triggers a function that does a lookup in a table where all the decoration expansions are stored, and then displays them in a hover. I'm going to play around with this a bit as that seems to be the simplest way probably.

**Comment by landerlo** [comment]
Yes, those are exactly my thoughts. Initially M.decoration was a table because one of the fields was a map from line number to the hover. Then we provide a function to pop up if there is something for that line.

**Comment by ckipp01** [comment]
Closed via #27
