### ISSUE TITLE
Leader Key Causes Compiling Message to Scroll Up

### ISSUE THREAD

**Issue by w-r-z-k** [scalameta/nvim-metals#302]
When I hit my leader key, the compiling message scrools up instead of staying on the bottom line.

I'm using the standard suggested metals configuration file.

<img width="959" alt="Screen Shot 2021-12-15 at 6 37 36 PM" src="https://user-images.githubusercontent.com/3805659/146281658-b0992c1d-9322-4c86-a2f7-3d9cdfd71dc2.png">

**Comment by ckipp01** [comment]
🤔 I've never seen this before. What is your leader key set to? Also is this using Lunarvim like in your other post or are you using only `nvim-metals`?

As a total aside, I'd also recommend setting `init_options.statusBarProvider = "on"` in your config table as this will provide a much better experience. The reason it's not on by default is that you need to ensure your capturing `g["metals_status"]` in your statusbar then. Either way, it's recommended to use.

**Comment by w-r-z-k** [comment]
Your recommendation eliminated the problem.  Thanks.

I uncommented `init_options.statusBarProvider = "on"` in your sample config and then added:

`lualine.setup({options = {...}, sections = {...,lualine_c = { 'g:metals_status' }, ...` 

to the `.config/nvim/lua/plugins/lualine.lua` file.  And now the message appears in the status bar.

Likely, when I had the message not in the status but at the bottom, it conflicted with some other plugin when I hit the `space` key (my leader key).

I am using @ChristianChiarulli's [Neovim-from-scratch](https://github.com/LunarVim/Neovim-from-scratch) which *I think* is an implmentation of his default [LunarVim](https://github.com/LunarVim/LunarVim) config expressed in a standardly configured fashion so people like me can mess with it using conventional nvim configuration knowledge.
