### ISSUE TITLE
Clean Install - nvim-metals Doesn't Show Errors

### ISSUE THREAD

**Issue by w-r-z-k** [scalameta/nvim-metals#306]
**Describe the bug**

I brought nvim back to a complete clean install.  No configuration except the sample [nvim-metals configuration](https://github.com/scalameta/nvim-metals/discussions/39).  When looking at some source code with an obvious error in it, I see nothing.  The status line says compiling and just keeps compiling.  If I do a `<leader>d` I get a Diagnostic window which contains no diagnostics.

**To Reproduce** Steps to reproduce the behavior:

1. Delete everything under `~/.config/nvim`, `~/.cache/nvim`, `~/.local/nvim`
2. Copy the [nvim-metals sample config](https://github.com/scalameta/nvim-metals/discussions/39) to `~/.config/nvim/init.lua`
3. Install packer: ```git clone --depth 1 https://github.com/wbthomason/packer.nvim\ ~/.local/share/nvim/site/pack/packer/start/packer.nvim```

4. Open nvim.  Run `:PackerSync` . Packer installs. Close nvim
5. Open nvim.  Open a `bad.scala` source file (with a syntax error in it) -- a simple 13 line, do-nothing `object extends App` type program  (see screenshot).  (This step is necessary I think to trigger the metals availability in order to install it -- sort of a strange bootstrapping step.)
6. Run `:MetalsInstall `. Close nvim
7. Open nvim.  Open a `bad.scala` source file (with a syntax error in it)
8. See no syntax errors. Status bar says: `LSP [metals][Log] Compiling aoc2021 13m1s (5%)` and counting
9. `<leader>d` . No errors listed. Exit nvim (`<leader>` is backslash since there's no config and that's the default)
10. At the command line: `scalac bad.scala`. See a syntax error(s).

When nvim starts up it complains about **dap** errors.  There's no `use ("mfussenegger/nvim-dap")` in the sample; so that's no doubt why.  I added the `use("mfussenegger/nvim-dap")` command in the sample config; did a `:PackerSync` ; restarted nvim; and this eliminated the dap error. But, as excepted it did not affect the problem.  I'm guessing this is a red herring but I wanted to stick with the standard config and install experience.

Additionally, I deleted the `.bloop`, `.metals`, `.bsp`, and `.ammonite` folders in the root of my project.  When I reopened the source file, this caused metals in nvim to ask for a reimport; which I did.  But this didn't affect the problem.

**Expected behavior**

I would expect errors in the diagnostics window.  To make this work like an IDE I think it needs to be configured with virtualtext messages, etc.  But I'm not sure if this is part of the sample config.  So barring that I would have at least thought there would be some diagnostics accessible from nvim.  That there is nothing in the diagnostics window and the status shows an infinite compile tells me there's something wrong somewhere.

**Screenshots**

I'm seeing no errors:
<img width="1239" alt="Screen Shot 2021-12-22 at 6 13 46 PM" src="https://user-images.githubusercontent.com/3805659/147166711-d4bc6118-1883-480e-9108-3757fc5867a9.png">

There are definitely compile errors:
<img width="1239" alt="Screen Shot 2021-12-22 at 6 14 20 PM" src="https://user-images.githubusercontent.com/3805659/147166726-85aab3a5-8940-4a8a-809b-990392aaaf0f.png">

Without the `use("mfussenegger/nvim-dap")` command there are extraneous errors:
<img width="1239" alt="Screen Shot 2021-12-22 at 6 14 44 PM" src="https://user-images.githubusercontent.com/3805659/147166739-2cad06c4-8196-49b7-a3ae-2b14dafb2a69.png">

If you remove the project `.metals` folder, you are invited to reimport the build:
<img width="1239" alt="Screen Shot 2021-12-22 at 6 30 42 PM" src="https://user-images.githubusercontent.com/3805659/147166767-f3742563-a2d6-4ee6-a189-58645377974d.png">

**Installation:**

- Operating system: macOS 11.6.1
- Nvim version: 0.6.0
- Commit of nvim-metals: **Where would I get this?** I just did a Packer install, so I assume nvim-metals is at the latest version.
- Metals version: 0.10.9

**Additional context**

Using a more sophisticated configuration I was able to get virtual text errors, status icons etc. and it was a somewhat useful IDE.  But it was very buggy and unstable.  I would get errors for my whole file for a while; then it would just show some error; then stop working.  It seemed really unstable.  So I had to go back to exiting to the shell and using scalac.  But at least I did get syntax highlighting and completions but not really the whole VisualCode type experience.  I could not tell if any of this was due to my configurations and plug-in so I decided to write this issue up using an install that did not have any of this potentially confounding stuff. 

Other functions such as K and gD seems to work fine.

**Search terms**

metals, nvim-metals, scala, nvim, IDE, issues, problems, configuration

**Comment by ckipp01** [comment]
Thanks for the detailed write-up @w-r-z-k, very helpful.

So playing with this a bit, you're hitting on an interesting problem that mainly has to do with standalone files. So a couple thoughts addressing your various points.

### Minimal configuration

Keep in mind that the configuration in https://github.com/scalameta/nvim-metals/discussions/39#discussion-82302 is meant as an example to show how various settings work. If you truly want the most minimal configuration possible, all you need is:

```lua
cmd([[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]])
```

I'll make this clearer in there that if you're trying to reproduce a bug, the above is a good place to start.

This is also why you're seeing the error messages about `nvim-dap`

```lua
-- Debug settings if you're using nvim-dap
local dap = require("dap")
```
Some of the settings in the example assume you already have it installed. To be safe I'll change this up a bit to make it clearer, thanks for pointing it out.

### The actual diagnostics issue

So the actual diagnostic issue you point out is a good one. What's happening is that when you directly open that file (I'm assuming it's just by itself?), then the file isn't in a valid workspace. So it's not actually part of a build target, meaning no diagnostics are being reported. You should see this if you look at the output of the Doctor.

<img width="1254" alt="Screenshot 2021-12-23 at 09 29 26" src="https://user-images.githubusercontent.com/13974112/147211711-58d1c5ea-5179-4efa-bf15-4e7d57b4682b.png">

Metals sorts of assumes or wants a workspace in order for everything to work correctly. In the case of a single file we do try to help out as much as we can providing some features, but as you experience, diagnostics aren't reported. There is historical reasons for this that are sort of implementation details (we don't report diagnostics from the presentation compiler).

For now, there are a couple ways around this.

1. Add this file to a valid build along your other sources. This will make it part of a build target and correctly report diagnostics
2. Make this file an ammonite or scala-cli script, which will then correctly report diagnostics
3. Make this file a `*.worksheet.sc` worksheet which will also then correctly report diagnostics

All together, I agree this is confusing behavior, so I'll create a ticket in the main Metals repo to try to get some more opinions on a possible way to make this clearer for standalone files. Thanks again for bringing this up.

**Comment by w-r-z-k** [comment]
Thanks.  This single file is actually part of a build.  The Metals Doctor reports all green checkmarks.  I should have screen-captured it.

I am opening that single file ala `nvim Day18.scala`.  It is under `aoc2021/src/main/scala`.  In the `aoc2021` projects file there's a `build.sbt`.  Metals asked to import it at some point.  There's a `.metals` folder at the project level (i.e. `aoc2021`).  What might be odd is that each of these `DayXX.scala` source files is its own standalone `object DayXX extends App {}` style program.

I will try this again with the proper minimal config.  Thanks.

(I'm working my way through _Advent of Code 2021_ in Scala 2 and trying to use all open source tools.  I did this last year using coc and decided to go with the native LSP this year.  As a vim coder I prefer not to use VSCode.)

**Comment by ckipp01** [comment]
Ah really? Is this project public by chance? I can't reproduce this if the file is in a build and that definitely shouldn't be happeneing.

**Comment by w-r-z-k** [comment]
Yes it's [here](https://github.com/w-r-z-k/aoc2021) .

**Comment by w-r-z-k** [comment]
With the minimal install, somehow I got packer installed.  Then I ran the one line `init.lua` with:

`vim.cmd([[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]])`

I erased all of the `.metals` folders I could find.  I did a `nvim Day18.scala` command in the `src/main/scala` directory.  Nothing.  No :Metals commands available.

I then went to the project root and entered `nvim build.sbt` . I was able to do a `:MetalsInstall`.  Then it asked me to import the _build.sbt_.  I think I exited and reeneterd nvim. I don't recall.

Then I `cd`'d to the `src/main/scala` folder. Then _nvim Day18.scala_.  It contains syntax errors.  It compiled.  No messages.  I did a `:MetalsRunDoctor`.  Nothing.  Not sure where the output of this would be anyways; in my previous config it came up in a window.  I have no keymaps, so I tried a `:lua vim.lsp.diagnostic.set_loclist()`.  Empty window appears.  Not sure what commands I should be issuing to see the errors.  No errors shown.   No virtual text or anything; maybe due to lack of configuration?  

For all I know this could be working properly.  But to the user it looks to not be doing anything useful.  Perhaps if I understood enough about the LSP API, I could write some hundred or so lines of correct code to make something work.  But the `:help lsp` documentation is impenetrable to the user.  Which is why I generally have to rely on some sample configuration.  On the other hand, there could be something on my system that is broken.  But I don't know what diagnostic I might consult to give me that info.  I'm not seeing any errors or complaints from nvim.

Packer plugins installed:
<img width="1239" alt="Screen Shot 2021-12-23 at 4 33 14 PM" src="https://user-images.githubusercontent.com/3805659/147295549-d484a614-5681-474a-8911-877e772d9991.png">

Inserted a couple nonsense lines in the source code:
<img width="1239" alt="Screen Shot 2021-12-23 at 4 57 17 PM" src="https://user-images.githubusercontent.com/3805659/147295604-04d71e06-5d06-47e3-84c4-023cee6aa021.png">

Trying to get at a syntax error list:
<img width="1239" alt="Screen Shot 2021-12-23 at 4 57 32 PM" src="https://user-images.githubusercontent.com/3805659/147295614-36385f71-3fad-45c4-bac4-2a91d0b84701.png">

**Comment by ckipp01** [comment]
Just to be sure in this scenario, your `.metals` dir is located in the root of your project correct? With your codebase I'm unable to reproduce this.

Can you paste the output of this for me: `:lua print(vim.inspect(vim.lsp.get_active_clients()))`

**Comment by w-r-z-k** [comment]
{
    _on_attach = <function 1>,
    attached_buffers = { true },
    cancel_request = <function 2>,
    commands = <1>{
      ["metals-debug-session-start"] = <function 3>,
      ["metals-run-session-start"] = <function 4>
    },
    config = {
      capabilities = {
        callHierarchy = {
          dynamicRegistration = false
        },
        textDocument = {
          codeAction = {
            codeActionLiteralSupport = {
              codeActionKind = {
                valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }
              }
            },
            dataSupport = true,
            dynamicRegistration = false,
            resolveSupport = {
              properties = { "edit" }
            }
          },
          completion = {
            completionItem = {
              commitCharactersSupport = false,
              deprecatedSupport = false,
              documentationFormat = { "markdown", "plaintext" },
              preselectSupport = false,
              snippetSupport = false
            },
            completionItemKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }
            },
            contextSupport = false,
            dynamicRegistration = false
          },
          declaration = {
            linkSupport = true
          },
          definition = {
            linkSupport = true
          },
          documentHighlight = {
            dynamicRegistration = false
          },
          documentSymbol = {
            dynamicRegistration = false,
            hierarchicalDocumentSymbolSupport = true,
            symbolKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }
            }
          },
          hover = {
            contentFormat = { "markdown", "plaintext" },
            dynamicRegistration = false
          },
          implementation = {
            linkSupport = true
          },
          publishDiagnostics = {
            relatedInformation = true,
            tagSupport = {
              valueSet = { 1, 2 }
            }
          },
          references = {
            dynamicRegistration = false
          },
          rename = {
            dynamicRegistration = false,
            prepareSupport = true
          },
          signatureHelp = {
            dynamicRegistration = false,
            signatureInformation = {
              activeParameterSupport = true,
              documentationFormat = { "markdown", "plaintext" },
              parameterInformation = {
                labelOffsetSupport = true
              }
            }
          },
          synchronization = {
            didSave = true,
            dynamicRegistration = false,
            willSave = false,
            willSaveWaitUntil = false
          },
          typeDefinition = {
            linkSupport = true
          }
        },
        window = {
          showDocument = {
            support = false
          },
          showMessage = {
            messageActionItem = {
              additionalPropertiesSupport = false
            }
          },
          workDoneProgress = true
        },
        workspace = {
          applyEdit = true,
          symbol = {
            dynamicRegistration = false,
            hierarchicalWorkspaceSymbolSupport = true,
            symbolKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }
            }
          },
          workspaceEdit = {
            resourceOperations = { "rename", "create", "delete" }
          },
          workspaceFolders = true
        }
      },
      cmd = { "/Users/user/.cache/nvim/nvim-metals/metals" },
      commands = <table 1>,
      filetypes = { "sbt", "scala" },
      flags = {},
      get_language_id = <function 5>,
      handlers = <2>{
        ["metals/executeClientCommand"] = <function 6>,
        ["metals/findTextInDependencyJars"] = <function 7>,
        ["metals/inputBox"] = <function 8>,
        ["metals/publishDecorations"] = <function 9>,
        ["metals/quickPick"] = <function 10>,
        ["metals/status"] = <function 11>,
        ["metals/treeViewDidChange"] = <function 12>
      },
      init_options = {
        compilerOptions = {},
        debuggingProvider = false,
        decorationProvider = true,
        didFocusProvider = true,
        disableColorOutput = true,
        doctorProvider = "json",
        executeClientCommandProvider = true,
        inputBoxProvider = true,
        quickPickProvider = true,
        statusBarProvider = "show-message",
        treeViewProvider = true
      },
      name = "metals",
      on_attach = <function 13>,
      on_init = <function 14>,
      root_dir = "/Users/user/Development/aoc2021",
      root_patterns = { "build.sbt", "build.sc", "build.gradle", "pom.xml", ".scala", ".git" },
      settings = {
        metals = {
          superMethodLensesEnabled = true
        }
      }
    },
    handlers = <table 2>,
    id = 1,
    initialized = true,
    is_stopped = <function 15>,
    messages = {
      messages = {},
      name = "metals",
      progress = {},
      status = {}
    },
    name = "metals",
    notify = <function 16>,
    offset_encoding = "utf-16",
    request = <function 17>,
    request_sync = <function 18>,
    requests = {},
    resolved_capabilities = {
      call_hierarchy = false,
      code_action = <3>{
        codeActionKinds = { "quickfix", "refactor", "source.organizeImports" }
      },
      code_lens = true,
      code_lens_resolve = false,
      completion = true,
      declaration = false,
      document_formatting = true,
      document_highlight = true,
      document_range_formatting = true,
      document_symbol = true,
      execute_command = true,
      find_references = true,
      goto_definition = true,
      hover = true,
      implementation = true,
      rename = true,
      signature_help = true,
      signature_help_trigger_characters = <4>{ "(", "[", "," },
      text_document_did_change = 1,
      text_document_open_close = true,
      text_document_save = <5>{
        includeText = true
      },
      text_document_save_include_text = true,
      text_document_will_save = false,
      text_document_will_save_wait_until = false,
      type_definition = false,
      workspace_folder_properties = {
        changeNotifications = false,
        supported = false
      },
      workspace_symbol = true
    },
    rpc = {
      handle = <userdata 1>,
      notify = <function 19>,
      pid = 2253,
      request = <function 20>
    },
    server_capabilities = {
      codeActionProvider = <table 3>,
      codeLensProvider = {
        resolveProvider = false
      },
      completionProvider = {
        resolveProvider = true,
        triggerCharacters = { ".", "*" }
      },
      definitionProvider = true,
      documentFormattingProvider = true,
      documentHighlightProvider = true,
      documentOnTypeFormattingProvider = {
        firstTriggerCharacter = "\n",
        moreTriggerCharacter = { '"' }
      },
      documentRangeFormattingProvider = true,
      documentSymbolProvider = true,
      executeCommandProvider = {
        commands = { "analyze-stacktrace", "bsp-switch", "build-connect", "compile-cancel", "compile-cascade", "compile-clean", "copy-worksheet-output", "extract-member-definition", "generate-bsp-config", "goto-position", "goto-super-method", "goto", "build-import", "insert-inferred-type", "new-scala-file", "new-scala-project", "reset-choice", "build-restart", "doctor-run", "file-decode", "sources-scan", "ammonite-start", "debug-adapter-start", "ammonite-stop", "super-method-hierarchy" }
      },
      foldingRangeProvider = true,
      hoverProvider = true,
      implementationProvider = true,
      referencesProvider = true,
      renameProvider = {
        prepareProvider = true
      },
      selectionRangeProvider = true,
      signatureHelpProvider = {
        triggerCharacters = <table 4>
      },
      textDocumentSync = {
        change = 1,
        openClose = true,
        save = <table 5>
      },
      workspaceSymbolProvider = true
    },
    stop = <function 21>,
    supports_method = <function 22>,
    workspaceFolders = <6>{ {
        name = "/Users/user/Development/aoc2021",
        uri = "file:///Users/user/Development/aoc2021"
      } },
    workspace_folders = <table 6>
  } }

**Comment by w-r-z-k** [comment]
The `.metals` folder is at the project root. (Though I have seen it under `/src/main/scala` also in the past).  Looking in there I see a `metals.log` and an error message:

`2021.12.23 20:48:25 ERROR code navigation does not work for the file '/Users/user/Development/aoc2021/src/main/scala/Day18.scala' because the SemanticDB file '/Users/user/Development/aoc2021/.bloop/aoc2021/bloop-bsp-clients-classes/classes-Metals-CDGBQVllTva221kjE79nOA==/META-INF/semanticdb/src/main/scala/Day18.scala.semanticdb' doesn't exist. There can be many reasons for this error. `

Googling for GitHub issues, someone suggested a `bloop compile root`.  So I did that.  I don't have bloop as a standalone program so I did a `cs install bloop`.  Then I did a `bloop compile root` at the project root.  An error occurred about not being able to find root.  So I look in `.bloop` and there's an `aoc2021`.  So I do a `bloop compile aoc2021` and I see this:

```
[W]  [E4] src/main/scala/Day15Stuff/Day15b.scala:23:32
[W]       procedure syntax is deprecated: instead, add `: Unit =` to explicitly declare `process`'s return type
[W]       L23:   def process(multiplier: Int) {
[W]                                           ^
[E] [E3] src/main/scala/Day15a.scala:1:8
[E]      Day15a is already defined as object Day15a
[E]      L1: object Day15a extends App {
[E]                 ^
[E] [E2] src/main/scala/Day15Stuff/Dijkstra.scala:5:12
[E]      Node is already defined as case class Node
[E]      L5: case class Node(name: (Int, Int))
[E]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[E] [E1] src/main/scala/Day15Stuff/Day15.scala:1:8
[E]      Day15 is already defined as object Day15
[E]      L1: object Day15 extends App {
[E]                 ^
[E] src/main/scala/Day15Stuff/Day15.scala: L1 [E1]
[E] src/main/scala/Day15Stuff/Dijkstra.scala: L5 [E2]
[E] src/main/scala/Day15a.scala: L1 [E3]
[E] src/main/scala/Day15Stuff/Day15b.scala: L23 [E4]
```

Hmmm, errors about previous days.  So I `nvim` one of these files and I see the errors in the virtualtext!  I try `nvim Day18.scala` and, as before, I see nothing.

I look in `.bloop/aoc2021.json` and see a lot of configuration but nothing about specific source files so I wonder how it thinks `Day15a.scala` is part of the project but not `Day18.scala`.  No where in my project am I specifying which `.scala` files under `/src/main/scala` are part of the project or not.

I am not managing bloop at all.  That's part of the plug-in and whatever it's riding on.  So I think this is a bug in the plug-in even though it might be bloop or metals to blame because from my point-of-view I am not managing these things.  Nor do I know how to configure them or how they work.  Nor do I consider `.bloop` nor `.metals` important from the user point-of-view.  It's possible that my deleting them in the past caused some issue; but I have deleted them since then and it doesn't make sense why old `Day15a.scala` shows errors and `Day18.scala` does not.

I should say that I see the exact same thing whether I access metals via `require'lspconfig'.metals.setup{}` or I use `nvim-metals` instead.  So though technically it's not an nvim-metals problem, I feel that since the plug-in is using these tools under the cover, it's not something the user of the plug-in is likely to be able to solve.

**Comment by ckipp01** [comment]
> but nothing about specific source files

You should actually see the following right up on top:

```
    "project": {
        "name": "aoc2021",
        "directory": "/Users/ckipp/Documents/scala-workspace/aoc2021",
        "workspaceDir": "/Users/ckipp/Documents/scala-workspace/aoc2021",
        "sources": [
            "/Users/ckipp/Documents/scala-workspace/aoc2021/src/main/scala",
            "/Users/ckipp/Documents/scala-workspace/aoc2021/src/main/scala-2.13",
            "/Users/ckipp/Documents/scala-workspace/aoc2021/src/main/scala-2",
            "/Users/ckipp/Documents/scala-workspace/aoc2021/src/main/java",
            "/Users/ckipp/Documents/scala-workspace/aoc2021/target/scala-2.13/src_managed/main"
        ],
...
```
That's actually taken from your project, so it should be exactly the same. Do you not see this here?

**Comment by w-r-z-k** [comment]
This `project` entry exists in the project root's `.bloop/aoc2021.jason` file.

When I edit Day15.scala I don't get any error reporting.  In the project root's `.metals/metals.log` file I see the ERROR message:

`2021.12.27 12:27:50 ERROR code navigation does not work for the file '/Users/user/Development/aoc2021/src/main/scala/Day15.scala' because the SemanticDB file '/Users/user/Development/aoc2021/.bloop/aoc2021/bloop-bsp-clients-classes/classes-Metals-GQugmYVbQSi7BxMPS_oD0w==/META-INF/semanticdb/src/main/scala/Day15.scala.semanticdb' doesn't exist. There can be many reasons for this error.`

And sure enough, there is no `classes-Metals-GQugmYVbQSi7BxMPS_oD0w==` file.  There is a `classes-Metals-KxuuTOd4SumSFfa8uhdHPg==` file, though.  So it looks like, at some point, when I relocated, or re-cloned my project, these `.bloop` files were wiped.  And the bloop system doesn't re-bootstrap itself; or metals doesn't re-bootstrap it; or something like that.  I've tried a `:Metals RestartBuild`. Since the user (me) isn't managing this stuff, it's hard to know what to do.  One would think that wiping the thing again would reset it.  But I must be missing some file somewhere when I do that.

A `:MetalsBuildConnect` doesn't solve the problem and gives an error in the metals log:

```
2021.12.27 13:38:32 INFO  no build target found for /Users/user/Development/aoc2021/.metals/.tmp/Main-4738558683853132452.scala. Using presentation compiler with project's scala-library version: 2.13.7[0m
Dec. 27, 2021 1:38:32 P.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
```

A `:MetalsCompileClean` gives the following message in the log but doesn't solve the problem:

`2021.12.27 13:40:06 INFO  compiling aoc2021 (27 scala sources)`

A `:MetalsImportBuild` seems to do a whole lot of things including a `sbt installBloop` but does not give errors and doesn't solve the problem.

A `:MetalsGenerateBspConfig` seems to trigger a recompile and I see the errors in the `metals.log` that I expect to see in vim.  So it doesn't solve the problem.

Tried some other `:Metals` commands.  No luck.

I did see an error in the vim messages (I was editing Day2.scala):

`[nvim-metals] Cannot find semanticDB for file:///Users/user/Development/aoc2021/src/main/scala/Day2.scala`

I wonder why there's no `:Metals` command to reset the whole thing so that it's not looking for old DB files.

I'll do some more experimenting with it.  Thanks for your help.  And thanks for writing nvim-metals!

**Comment by ckipp01** [comment]
I'm sorry you're having to go through so much trouble for this.

Regarding the `.bloop/` files, just to expalin the procoess a bit since you tried a whole bunch of stuff

- `:MetalsImportBuild` should do everything you needed up above. It will re-export your build, making sure everything is up to date. Then when you trigger a compile it should re-generate the necessary semanticDB files.
- `:MetalsGenerateBspConfig` shouldn't be necessary here. In fact, this probably switched your build server from Bloop over to sbt, which means it's not even looking at your `.bloop/ ` dir anymore. You can verify this if you do the `:MetalsDoctor` and it will show you the build server you're using. You can also try the `:MetalsSwitchBsp` command to switch back to Bloop.

I'll admit there is a lot of moving pieces behind the scenes which make it all a bit confusing. If you are looking for somewhat of an overview, I do have a video on there here: https://youtu.be/fpzN_vTBy18

**Comment by w-r-z-k** [comment]
I submitted a metals bug [#3407](https://github.com/scalameta/metals/issues/3407).

**Comment by w-r-z-k** [comment]
On the other hand it seems to be picking up some errors but not others.  Very frustrating to debug this:
<img width="1239" alt="Screen Shot 2021-12-27 at 2 55 44 PM" src="https://user-images.githubusercontent.com/3805659/147503285-97a8c08f-0e59-477e-8734-d13380231350.png">

**Comment by w-r-z-k** [comment]
I have figured out how to recreate the problem.  **The bottom line**: _The errors reported in nvim in the file you are editing are based on the results of an overall sbt build not on the errors currently in the file you are editing._ 

In my `src/main/scala` folder I have scala files: `Day1.scala`, `Day2.scala` etc. 

But I also have a subfolder `Day15Stuff` in which there is an alternative version of `Day15.scala`.  (This is not in my public repo.) If I do an `sbt clean` `sbt compile` from the project root, the compiler will correctly complain that this file contains an object (Day15) that is already defined and it will not produce any further errors.  I don't know why the compile stops here.  And if I edit any of the files in the `src/main/scala` folder with nvim (say `Day18.scala`), I do not get the errors which I get with a `scalac Day18.scala`.  (See screenshot and scalac output below.)

<img width="1239" alt="Screen Shot 2021-12-27 at 4 46 16 PM" src="https://user-images.githubusercontent.com/3805659/147509262-b321f3a6-d8bc-42cb-b510-bbac532cfd4d.png">

```
Day18.scala:3: error: not found: value hello
  hello!
  ^
Day18.scala:9: error: not found: value hello
   hello
   ^
Day18.scala:11: error: not found: value polly
  polly
  ^
Day18.scala:3: error: postfix operator ! needs to be enabled
by making the implicit value scala.language.postfixOps visible.
This can be achieved by adding the import clause 'import scala.language.postfixOps'
or by setting the compiler option -language:postfixOps.
See the Scaladoc for value scala.language.postfixOps for a discussion
why the feature needs to be explicitly enabled.
  hello!
       ^
4 errors
```

If I remove that `Day15Stuff` folder and do an `sbt clean` `sbt compile` from the project root, the compiler will give me all of the errors.  And behold, upon editing the source file again I get the full errors, as below.

<img width="1239" alt="Screen Shot 2021-12-27 at 4 42 49 PM" src="https://user-images.githubusercontent.com/3805659/147509314-c4d02eb6-2446-46b7-adca-d10dc3641d5c.png">

There must be something about how this complicated toolchain works that I don't understand and that prevents the incremental compiler from reporting errors up through metals to nvim-metals to nvim. 

It's counter-intuitive to the user because, when you edit a given file, you would expect to see the errors that you would see if you did a simple `scalac Day18.scala`, as below.  _The errors reported in nvim in the file you are editing are based on the results of an overall sbt build not on the errors currently in the file you are editing._   Whether or not that's a bug I suppose is a matter of opinion but it's something to be aware of.
