### ISSUE TITLE
MetalsInstall (coursier) doesn't work on Apple Silicon (M1)

### ISSUE THREAD

**Issue by ironfish** [scalameta/nvim-metals#329]
### Describe the bug

Below is what I get when opening a Scala for the first time. This is expected

<img width="1260" alt="Screen Shot 2022-01-24 at 8 10 27 PM" src="https://user-images.githubusercontent.com/1911792/150895751-0c150312-7e2c-4dcb-b8ef-99f13b41ab70.png">

When I run `:MetalsInstall` I get the following error.

<img width="1410" alt="Screen Shot 2022-01-24 at 8 12 13 PM" src="https://user-images.githubusercontent.com/1911792/150895869-2fea3982-1790-462d-a8bc-028066449dd2.png">

### Expected behavior

Metal's Install to run and install correctly.

### Operating system

macOS

### Version of Metals

v0.11.1

### Commit of nvim-metals

Cannot Find as Metals will not install.

**Comment by ironfish** [comment]
Okay I was able to get `:MetalsInstall` to work after Installed Rosetta. It looks like `Coursier` needs to release a version that fully works with ARM.

**Comment by ckipp01** [comment]
Hey @ironfish, thanks for reporting. I'll leave this open to help discovery in case others hit on this. As you already found it it seems, there are issues with Coursier on M1. I see you already commented on them 😆 but I'll link them here as well:

- https://github.com/coursier/coursier/issues/2069
- https://github.com/coursier/coursier/issues/2335

**Comment by ckipp01** [comment]
Hey @ironfish, it looks like coursier [merged in](https://github.com/coursier/coursier/commit/f76cb8c8c9aaafd1d95a3d39811cf6a1174e812e) support for Graal 22.1.0 from my understanding supports M1. Do you know if this fixes your install woes?

**Comment by ckipp01** [comment]
Great, thanks for reporting on this @reidrac. I'll go ahead and close. If others hit on this, please do report back.
