### ISSUE TITLE
documentation improvement: metals memory settings

### ISSUE THREAD

**Issue by svalaskevicius** [scalameta/nvim-metals#333]
### Describe the feature

Hi,

Would it be possible to document how to configure the JVM memory settings for metals? (gc, Xmx etc)

I've tried to look at https://github.com/scalameta/nvim-metals/blob/main/doc/metals.txt but cannot seem to find it there (nor on the website https://scalameta.org/metals/docs/editors/vim)

Thanks

**Comment by ckipp01** [comment]
Hey @svalaskevicius thanks for the request! For sure, I can try to make this clearer. There is actually a fair amount of stuff that goes into this. It looks at the `.jvmopts` file and also grabs a few other things. You can see some of the logic here: https://github.com/scalameta/nvim-metals/blob/main/lua/metals/jvmopts.lua. Let me try to come up with some illustrations and figure out the best place to put some more info.

**Comment by ckipp01** [comment]
Hey @svalaskevicius getting back to this, actually looking further into this, did you read the docs for `serverProperties`. This is actually what you'll want to use for this:

```
serverProperties                                              *serverProperties*

Type: table ~
Default: {} ~

Table of properties to pass along to the Metals server. By default, the
environment variable `JAVA_OPTS` and the `.jvmopts` file are respected.
However, we care most about the proxy settings from those places, not
necessarily the memory options since Metals has different requirements for
example than sbt. So if you have proxy settings defined in `JAVA_OPTS`, then
no need to define them here again. However, if you want to set some spefic
memory settings for Metals, then this is the place. 
```

So thinking about documenting this more, do you have any recommendations on how to make this easier for people to find or to use?

**Comment by svalaskevicius** [comment]
Hi, I've completely missed it! Thanks! 

My search in the docs was based on various forms of `java`, `opts`, `Xmx` and similar keywords, and I'd stumbled at least twice on java home and ammonite jvm opts.

Maybe just some similar search keywords for other users would be beneficial, or crosslinking java home option to this?

Thanks again :)
