### ISSUE TITLE
Plugin breaks on neovim 0.6

### ISSUE THREAD

**Issue by mweisshaupt1988** [scalameta/nvim-metals#377]
### Describe the bug

The recent changes utilize functions that are only present in the latest Neovim 0.7 release. Not all package managers have been updated yet.

I would appreciate if you tagged the commit before the breaking change and provide a short hint on how to pin the plugin until the neovim update is available.

FYI, I did it this way
Plug('https://github.com/scalameta/nvim-metals.git', { commit = '049646944796674fb221136b2440eee0c7102ab0' })

### Operating system

Linux

### Version of Metals

latest

### Commit of nvim-metals

HEAD

**Comment by ckipp01** [comment]
Thanks for the report @mweisshaupt1988. I've always been pretty clear that I only support the latest stable version of Neovim. 0.7 is a requirement as it says in the README, in the docs, and I announced it in the [breaking changes])https://github.com/scalameta/nvim-metals/discussions/253) discussion which I recommend following.

> I would appreciate if you tagged the commit before the breaking change and provide a short hint on how to pin the plugin until the Neovim update is available.

This is a good idea. In the future when this happens I'll do this. Up until this point there has been very few breaking changes so I haven't feel the need to actually version, but I can improve this in the future. Thanks for bringing it up.
