### ISSUE TITLE
Odd behavior with scaladoc completions

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#38]
**Describe the bug**

Normally when you are adding in a Scaladoc and you're at this point `/**` Metals will give you a completion option for the full scaladoc of whatever you're over. This happens in the other Metals extensions, but seems to not be the case with nvim-metals.

**To Reproduce** Steps to reproduce the behavior:

1. Make a case class
2. Attempt to create a scaladoc
3. See that no completion items come from the server

**Expected behavior**

I'd expect to get the scaladoc completion item.

**Installation:**

- Operating system: macOS
- Nvim version: `v0.5.0-dev+5ce328df4`
- Metals version: `0.9.8+10-334e402e-SNAPSHOT`

**Comment by ckipp01** [comment]
Doing a little digging, it seems that nvim doesn't yet support context completions, which is what triggers scaladoc completions. This probably won't be able to happen until it's added upstream.

**Comment by ckipp01** [comment]
So it looks like this _is_ working now, but for my local setup I get some odd behavior with the docs shifting over too far.


![2021-05-10 14 14 36](https://user-images.githubusercontent.com/13974112/117657693-280db900-b19a-11eb-9217-0700a5ff286f.gif)

**Comment by jsatk** [comment]
It appears the issue is that it continuously indents the scaladocs more and more the deeper in the "nest" you are. See example video demoing it here. http://i.jsatk.us/7CkTTO

**Comment by ckipp01** [comment]
> Is this issue exclusive to metals-nvim? Not present in VS Code + Metals?

Correct. My guess is that it actually has something to do with the vim-scala indentation. Probably metals returns the completion with some tabs, and at the same time the newline triggers the indentation rules to indent. Therefore leading to too many tabs.

**Comment by ckipp01** [comment]
Also total aside @jsatk but your video made me realize that the empty resolve seems to have snuck back into compe. https://github.com/hrsh7th/nvim-compe/pull/463

**Comment by ckipp01** [comment]
I don't see this happening for me anymore so I'm going to go ahead and close. If someone else is still hitting on this, please let me know.
