### ISSUE TITLE
Scala 3 project seems to be using Scala 2

### ISSUE THREAD

**Issue by danbills** [scalameta/nvim-metals#418]
### Describe the bug

1. run `sbt new scala/scala3.g8 `
1. start neovim
1. run `:MetalsDoctor`
1. Observe `target type: Scala 2.12.15`

I noticed on a more complex scala3 project that metals was calling out things as though it was expecting Scala 2.  So I tried this minimal example and it seems clear that something is misconfigured. for Metals.

### Expected behavior

Target Type should be scala3

### Operating system

macOS

### Version of Metals

v0.11.6   

### Commit of nvim-metals

?

**Comment by ckipp01** [comment]
Just for kicks, what does `:MetalsInfo` show you?
