### ISSUE TITLE
MetalsToggleLogs crops the logs

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/nvim-metals#430]
### Describe the bug

`:MetalsToggleLogs` results in logs being cropped in the beginning.

### Expected behavior

`:MetalsToggleLogs` shows complete log.

### Operating system

Linux

### Version of Metals

0.11.7

### Commit of nvim-metals

fa5245876d32182c9bd893a00857ffa58decb3c6

**Comment by ckipp01** [comment]
This isn't really possible with how it's currently set up. Currently under the hood it's literally just doing a `tail -f .metals/metals.log`, which means it starts tailing when the command is issues. Sometimes this file can be huge, so I wouldn't want to display the whole thing. If you need to see the full thing you're still able to just open that file if you want. So I guess the order should change a bit then, just open it first, then trigger the event you'd like to check in the logs.

**Comment by arbitrary-dev** [comment]
From my stand point logs are opened when you already experienced something strange.

Perhaps `-n100` could be used...
```
$ man tail
...
       -n, --lines=[+]NUM
              output  the  last NUM lines, instead of the last 10; or use -n +NUM
              to output starting with line NUM
```

But whatever, I see your point.

**Comment by ckipp01** [comment]
> Perhaps -n100 could be used...

Sure that might be a good idea. I'll play with this.
