### ISSUE TITLE
Symbols highlighting doesn't work until JDK sources attached

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/nvim-metals#431]
### Describe the bug

1. [Setup](https://github.com/scalameta/nvim-metals/discussions/428#discussioncomment-3128718) symbols highlighting
2. Try it with JDK that have no sources attached (you should get "Code navigation will not work for X build targets" notice on project import, see #427)
3. It doesn't work :(

### Expected behavior

Even though my system's JDK doesn't have source files to navigate through, I still expect to have symbol & its references highlighting in my Scala projects.

### Operating system

Linux

### Version of Metals

0.11.7

### Commit of nvim-metals

fa5245876d32182c9bd893a00857ffa58decb3c6

**Comment by ckipp01** [comment]
Thanks for the report @arbitrary-dev, although I've never seen this happen and not having jdk sources shouldn't have any effect on symbol highlighting in your *Scala* sources. If you were in a Java file, then sure, but not in Scala. Can you try this again with a minimal hello world project in Scala?

**Comment by ckipp01** [comment]
Going to close since I never got any more feedback. Feel free to comment back if you have more info.
