### ISSUE TITLE
Symbols highlighting have ~5s delay

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/nvim-metals#432]
### Describe the bug

1. [Setup](https://github.com/scalameta/nvim-metals/discussions/428#discussioncomment-3128718) symbols highlighting
2. Try it out
3. Symbols highlighting have ~5s delay

### Expected behavior

It works almost immediately, just like `:lua vim.lsp.buf.document_highlight()` does.

### Operating system

Linux

### Version of Metals

0.11.7

### Commit of nvim-metals

fa5245876d32182c9bd893a00857ffa58decb3c6

**Comment by ckipp01** [comment]
> You can set it to one second as follows: :set updatetime=1000. Or choose any other number that suits you.

Yup, this is exactly what I was going to mention. You'll need to update this. Thanks for the answer @antosha417! I'll go ahead and close this. @arbitrary-dev if you still have issues after this, feel free to comment back.
