### ISSUE TITLE
Display decoded definitions form same file in different buffers

### ISSUE THREAD

**Issue by susliko** [scalameta/nvim-metals#459]
### Current behavior
Showing javap/tasty/semanticdb representations of definitions is a great feature ❤️ 
In case there are multiple trait/class/object definitions in the same file, a popup asks for a choice of a single definition to decode.
Then decoding result is displayed in a separate buffer named "%filename%.scala decoded *%format% viewer".
The buffer is [reused](https://github.com/scalameta/nvim-metals/blob/b7587a9155d22761f1b28c18f7927e6df0d08387/lua/metals/decoder.lua#L62) when decoding other definitions from that file.

### Proposal
I'm not sure if reusing the buffer is a convenient default behavior, since it makes impossible showing same-type decodings (e.g. javap) for multiple definitions from the same file at the same time.
Also, it might be useful to put definition names into the buffer name, e.g "%filename%.scala/%classname% decoded %format% viewer"

**Comment by ckipp01** [comment]
Hey @susliko, good point. I haven't revisited this since I first implemented it. My original thought process was to try and make sure there wasn't a bunch of random leftover buffers for decoded classes etc, but I was probably overzealous with my worry.

> Also, it might be useful to put definition names into the buffer name, e.g "%filename%.scala/%classname% decoded %format% viewer"

Yea, I think this is a totally fine idea.
