### ISSUE TITLE
String comparison of metals server versions fails in certain cases.

### ISSUE THREAD

**Issue by buntec** [scalameta/nvim-metals#482]
### Describe the bug

When using a custom metals server version, the Scala binary version is selected based on a string comparison against "0.11.2" in `install.lua`. This fails for, e.g., "0.11.10" because `"0.11.10" > "0.11.2"` evaluates to false. 

### Expected behavior

Select 2.13 binaries for all server versions higher than "0.11.2".

### Operating system

Linux

### Version of Metals

latest

### Commit of nvim-metals

2a60af7dfe2daf6b4635c81d3241304eaa7bb741

**Comment by ckipp01** [comment]
Duplicate of #481
