### ISSUE TITLE
TVP window keeps popping up again and again after being closed

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/nvim-metals#489]
### Describe the bug

TVP window keeps popping up again and again after being closed with either `:bw` or `<C-w>c`.

The window initially casted by:
```
:map
...
n  \tr         * <Cmd>lua require("metals.tvp").reveal_in_tree()<CR>
```

\+ there's one more issue with TRP. When casting it for the first time (`reveal_in_tree()`) I see only empty nodes for "Projects" & "Libraries", and then compilation kicks off. And then, after some time, I call `reveal_in_tree()` again and it works as expected, with nodes populated and cursor jump to a current position.

```
$ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Expected behavior

TVP window not pop up again when not explicitly requested for.

### Operating system

Linux

### Version of Metals

0.11.9

### Commit of nvim-metals

89fe30e78db91584453821f54503b7931029886d

**Comment by arbitrary-dev** [comment]
I have a suspicion that it happens when I do writes to the buffer `:w`

**Comment by arbitrary-dev** [comment]
Closing it with `.toggle_tree_view()` helps though.

**Comment by arbitrary-dev** [comment]
Would be nice to have `q` mapped to close the tree, as is the case with NERDTree.

**Comment by ckipp01** [comment]
Thanks for the report @arbitrary-dev. Playing around a bit I see the issue. In theory when the window is closed a `metals/treeViewVisibilityDidChange` should be sent to the server letting it know that it's no longer visible. Then Metals won'd send any `metals/treeViewDidChange` notifications to the client. Since that doesn't happen metals keeps firing them.

**Comment by ckipp01** [comment]
> Would be nice to have q mapped to close the tree, as is the case with NERDTree.

There exists a toggle that can be used for this with `toggle_tree_view`. This can be custimized as well. It's preferable to use this over deleting the buffer every time in order for Metals to not have to re-compute the entire tree over again.
