### ISSUE TITLE
Rename says "Nothing to rename" on second rename

### ISSUE THREAD

**Issue by w-r-z-k** [scalameta/nvim-metals#506]
### Describe the bug

If you rename a symbol with:

`lua vim.lsp.buf.rename()`

the symbol is renamed.  If you try to rename that symbol again to something else, you get the message:

`Nothing to rename`

### Expected behavior

You should be able to rename the symbol.

### Operating system

macOS

### Version of Metals

v0.11.9

### Commit of nvim-metals

where would I find this?

**Comment by ckipp01** [comment]
Hey @w-r-z-k thanks for the report. I think this is sort of working as expected unless you missed a step. After you do the first rename, you need to save the file. After you save you'll then be able to do the rename again. If you don't do the safe, the buffer contents will have changed, and we really can't safely do a rename in that instance.

Did you save between rename tries?

**Comment by w-r-z-k** [comment]
Oh!  Right you are!  It works.  Thanks.
