### ISSUE TITLE
How to change "*.worksheet.sc" to not conflict with supercollider?

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#509]
### Discussed in https://github.com/scalameta/nvim-metals/discussions/508

<div type='discussions-op-text'>

<sup>Originally posted by **w-r-z-k** December 13, 2022</sup>
It seems if I open a new worksheet with the file extension ".worksheet.sc", it will recognize it as Scala.

But if I open an existing one, sometimes it recognizes it as a [supercollider](https://en.wikipedia.org/wiki/SuperCollider) program.

I think there's some settings in my neovim setup that recognizes purely on the last dot.  But unfortunately, I cannot find what that might be.  It's likely buried quit deep in the neovim software or a plugin.

Is there a way to set the Scala worksheet extension to, say, ".worksheetsc" (i.e. with out the extra dot)?

Thanks</div>

**Comment by ckipp01** [comment]
Thanks for the report @w-r-z-k. I've been seeing an increasing amount of users hit on this recently so I'll move this to an actual issue. I'm guessing that you have a space between your variable and type declarations like this:

```scala
val example : String = "hi"
```

The ` : ` pattern is problematic in Scala script since the filetype detection will think think this is supercollider code. The issue stems from [here](https://github.com/neovim/neovim/blob/29b80f6f2e9391b5d78390f65d09f00f73829310/runtime/lua/vim/filetype/detect.lua#L1100) in Neovim, but before we can change that it'll need to change in Vim. I've sent a pr in to address this in https://github.com/vim/vim/pull/11699. This should be a pretty safe change, so hopefully it'll be accepted. Then we can update this in Neovim as well and avoid this since it's starting to get a bit annoying.

**Comment by ckipp01** [comment]
> Is there a way to set the Scala worksheet extension to, say, ".worksheetsc" (i.e. with out the extra dot)?

Regarding this question though, no, Scala convention for script is `.sc`. A lot of things rely on this, so it won't change. The `*.worksheet.sc` is the Metals convention for worksheets.

**Comment by w-r-z-k** [comment]
There are no semicolons in my worksheet.  So it must be a wider recognition issue.

I tried to figure out what it was but could not.  However, I narrowed it down to one line.  It does not like line 7 here:

```
1. val f = Source.fromFile("../../../data/Day4.example.txt")
2. 
3. val lines = f.getLines().toList
4. 
5. lines.count(x => {
6.    val a = x.split(Array('-',','))
7.    (a(0) >= a(2) && a(1) <=a (3)) || (a(2) <= a(0) && a(3) <= a(1))
8. })
```
If I remove that line, it's a scala file.  With it in, a supercollider file.

I wonder why it needs to recognize the file.  I told it that it was a `.worksheet.sc` file.  I should be able to put garbage in that file since scala, especially, amongst programming languages, can vary widely in appearance. 

Thanks for sending in the PR.

**Comment by w-r-z-k** [comment]
Now that I look at the [lua file](https://github.com/neovim/neovim/blob/29b80f6f2e9391b5d78390f65d09f00f73829310/runtime/lua/vim/filetype/detect.lua) you mentioned, I think I might see the problem.

Don't know lua but I wonder if line 1104:

`'|%w*|',`

could mean _vertical bar following by zero spaces followed by vertical bar_ which is the OR symbol in my worksheet. And in fact, if I change that to `&&`, say, and re-open the file, it's a scala file again.

Maybe line 1104 should be something like:

`'|%w+|',`

but I'm just guessing.

**Comment by ckipp01** [comment]
Good catch @w-r-z-k, I think you're correct after playing around with it a bit. I've gone ahead and updated the pr with this.

**Comment by ckipp01** [comment]
Alright @w-r-z-k if you use nightly this should now be taken care of. The Vim patch was merged and the follow-up Neovim was as well in https://github.com/neovim/neovim/commit/4a78ed60a3acd3a5694cc34debd4d91bed96195a.
