### ISSUE TITLE
Allow specification of "mainClass" and "buildTarget" DAP keys

### ISSUE THREAD

**Issue by trmckay** [scalameta/nvim-metals#513]
### Describe the feature

I work on a large project with many build targets. I am rarely working inside the one that contains the `main` I want to debug. I would like to be able to launch a configuration that runs a configuration with a specific `mainClass` no matter what Scala file I am editing. Currently, I need to switch to the file that contains `main` to start the debug session.

### Potential ways to implement

[I think it is possible to specify a main class](https://scalameta.org/metals/docs/integrations/debug-adapter-protocol/#via-explicit-main-or-test-commands) (VSCode supports this).

Without reading the source too carefully:

- Pass `mainClass` [here](https://github.com/scalameta/nvim-metals/blob/d1c01907256dae7c9d55ba1fcfb8cf6b4f583325/lua/metals/setup.lua#L108).
- I imagine something will need to change for configuration selection since these may not correspond to the current build target.

I'm going to take a shot at implementing this, so I'd appreciate any tips.

**Comment by ckipp01** [comment]
Hey @trmckay, thanks for opening this! You're exactly right. I actually had thought this was already supported, but looking closer you're right. According to the [docs](https://scalameta.org/metals/docs/integrations/debug-adapter-protocol) there are basically two ways to trigger this, using debug discovery, which nvim-metals is doing now, or explicitly passing the `mainClass` and `buildTarget`. It should be simple enough to add a check that if in the user config if `mainClass` exists, then don't pass the `runType` and instead pass the `mainClass` and `buildTarget`. If it doesn't exist, then we default to `runType` like we currently do. Let me know if you need any other pointers!
