### ISSUE TITLE
Open metals' logs relatively to LSP-root

### ISSUE THREAD

**Issue by susliko** [scalameta/nvim-metals#530]
### Describe the bug

In the following project structure:
```
app
  ui/
  server/
    build.sbt
    src/main/scala/Main.scala
```
1. Start nvim with `app` as a root directory
2. Go to Main.scala. Metals launches with a root at `app/server`
3. Toggle Metals logs. A buffer with a tail of `app/.metals/metals.log` opens 

The use case is caused by a desire to develop multiple components (potentially in different languages) in a single nvim instance

### Expected behavior

A buffer with a tail of `app/server/.metals/metals.log` opens

### Operating system

macOS

### Version of Metals

v0.11.10

### Commit of nvim-metals

c552c96b837ce8b1318cf3eccbda41a73760cb21

**Comment by ckipp01** [comment]
Thanks a lot for opening this @susliko. While trying to reproduce this I actually hit on another issue, which I _think_ is sort of pointing out a flaw somewhere, but I need to dig in a bit further to figure it out. For example if I have
```
.
├── build.sc
├── minimal
│  ├── src
│  │  └── Main.scala
```
And I open `build.sc` all is fine and the `.metals` dir gets created there like I'd expect. If I then exit and `cd minimal/src` and open there, I also see another `.metals/` created there. The log there still says it recognizes the right root, and that the logs are going to the other `.metals/metals.log`, but there shouldn't be another `.metals/` created. I'm not sure why that's happening now especially seeing that the correct root is _still_ being detected. This might be an issue in Metals actually. I want to confirm that first and ensure we're not getting extra `.metals/` dirs created, and then we can address the issue you mentioned @susliko.

**Comment by susliko** [comment]
@ckipp01 I can confirm that running nvim from `./minimal/src` in your example (in sbt project though) and entering Main.scala results in an extra `./minimal/src/.metals` directory. Its `metals.log` file contains the following lines:
```
2023.01.24 12:51:55 INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at PATH_TO_REPRO/repro/minimal/src/.metals/lsp.trace.json or ....
2023.01.24 12:51:55 INFO  logging to file PATH_TO_REPRO/repro/.metals/metals.log
```

**Comment by ckipp01** [comment]
Alright, @susliko are you able to try this again using `0.11.10+79-399623cf-SNAPSHOT`? I believe this should be fixed.

**Comment by susliko** [comment]
@ckipp01 Sorry for the delay
Tested on locally published metals from commit https://github.com/scalameta/metals/commit/85e9f3acafeec7cc9fb4cab65c5578b88c593f15 (because sonatype timeouted when downloading snapshot 🤷🏻)

1. The case when `build.sbt` is collocated with the project root and we enter `./minimal/src` is handled correctly: no extra `.metals` directories created, nvim-metals opens log file from the root
2. The original case of this issue, when `build.sbt` if located in one of a few modules of the project, still reproduces: both `app/.metals` and `app/server/.metals` directories are created and nvim-metals shows logs from the first one. These logs reference to the nested log file:
```
2023.01.27 11:20:51 INFO  logging to file  ..../app/server/.metals/metals.log
```

**Comment by ckipp01** [comment]
@susliko just to double-check, can you give #533 a try?

**Comment by susliko** [comment]
@ckipp01 Yep, the fix works, nvim-metals opens a more nested log file 🙇🏻 

What about .metals directory, which is still created in the project root? Is it an acceptable behaviour or should it be fixed in Metals?

**Comment by ckipp01** [comment]
> What about .metals directory, which is still created in the project root? Is it an acceptable behaviour or should it be fixed in Metals?

This shouldn't be happening. Metals should only create it either in the global log file or in the root uri that is passed in. However, again you'll need the nightly for this fix. With the latest snapshot if this is still happening, do you mind creating a reproduction where this happens that I can use to mimic it?

**Comment by susliko** [comment]
Just for the history: I was unable to reproduce it with the latest snapshot of Metals
