### ISSUE TITLE
No metals commands available

### ISSUE THREAD

**Issue by thomhughes** [scalameta/nvim-metals#531]
### Describe the bug

I've installed 'nvim-metals' using packer and it's successfully installed. However, none of the commands are available to me. 

`local nvim_metals_group = vim.api.nvim_create_augroup("nvim-metals", { clear = true })
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "scala", "sbt" },
	callback = function()
		require("metals").initialize_or_attach({})
	end,
	group = nvim_metals_group,
})
`

I have this in `.config/nvim/after/plugin/metals.lua` and calling `require('metals')` gives no errors. What am I meant to do?

### Expected behavior

`MetalsInstall` is meant to be an editor command.

### Operating system

macOS

### Version of Metals

v0.11.10

### Commit of nvim-metals

c552c96b837ce8b1318cf3eccbda41a73760cb21

**Comment by ckipp01** [comment]
Hey @thomhughes, just to make sure, since this is a `FileType` autocmd you need to make sure you're opening a Scala file, and then the commands will be available to you. Did you try this after opening a Scala or sbt file?

**Comment by ckipp01** [comment]
So this has been a few months old now and I've gotten no other response, so I'm going to go ahead and close. Please do feel free to report back if you have more info and want this re-opened.
