### ISSUE TITLE
It looks like you don't have Metals installed yet.

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/nvim-metals#535]
### Describe the bug

Getting this on startup...
```
[nvim-metals] Welcome to nvim-metals!
[nvim-metals] It looks like you don't have Metals installed yet.
[nvim-metals] 
[nvim-metals] You can do this using `:MetalsInstall`.
[nvim-metals] 
[nvim-metals] If you need to set a specific version, you can set it in your settings table.
Press ENTER or type command to continue
```

Even though `.metals` folder is present from previous run.

### Expected behavior

Metals starts normally.

### Operating system

Linux

### Version of Metals

v0.11.10

### Commit of nvim-metals

0b9c530

**Comment by arbitrary-dev** [comment]
My config:
https://github.com/arbitrary-dev/common-configs/blob/master/user/.config/nvim/lua/nvim-metals.lua

**Comment by ckipp01** [comment]
> Even though .metals folder is present from previous run.

Just because there is a `.metals` present has nothing to do with whether or not Metals is actually installed. The message you posted says:

```
[nvim-metals] It looks like you don't have Metals installed yet.
[nvim-metals] 
[nvim-metals] You can do this using `:MetalsInstall`.
```

Did you try `:MetalsInstall`?

**Comment by arbitrary-dev** [comment]
>Did you try `:MetalsInstall`?

As I said, `.metals folder is present from previous run` and in that previous run I already called `:MetalsInstall`, that's why I'm wondering, why it keeps asking me for it again.

**Comment by ckipp01** [comment]
> As I said, .metals folder is present from previous run

Again... having a `.metals` folder literally has _nothing_ to do with running `:MetalsInstall`.

It seems that either the Metals installation must have not worked as expected, somehow the Metals binary got removed, or something else. If you're getting that message I'm assuming a `:MetalsInfo` won't work either correct? Either way, can you try a `:MetalsInstall` again, and after doing that re-open. Does it continue to happen? If it does, can you look inside of `vim.fn.stdpath("cache")` and look inside the  `nvim-metals` dir? In there is where `metals` should be. You should also see a `nvim-metals.log` in there that might have some info about what happened during the install.

**Comment by arbitrary-dev** [comment]
>somehow the Metals binary got removed

Where it gets installed though?

**Comment by arbitrary-dev** [comment]
Ah, I see...

```
:lua print(vim.fn.stdpath("cache"))
/tmp/user/.cache/nvim
```

My `/tmp` directory is under `tmpfs` and cleared after every reboot.

Mystery solved.
