### ISSUE TITLE
Install metals by cs or coursier

### ISSUE THREAD

**Issue by chms7** [scalameta/nvim-metals#536]
### Describe the feature

In my system (LinuxMint 20.3, based on Ubuntu20.04), the `cs` doesn't work due to the problem of `libc.so.6: version GLIBC_2.32 not found` . However the `coursier` works well with scala and metals on vscode. 
When I open nvim it shows:
```
It looks like you don't have Metals installed yet
```
After I run `:MetalsInstall` it shows this while the log contains nothing, even after I run `coursier install metals` it still doesn't work:
```
Something went wrong with the Metals install. Please check the logs
```
It's probably the problem of calling sequence of `cs` and `coursier`, because when I edit the `~/.local/share/nvim/site/pack/packer/start/nvim-metals/lua/metals/config.lua` from:
```
local function check_for_coursier()
  -- this must be first the second "cs" is also found as binary but we should
  -- be more specific on Windows
  if util.is_windows and util.has_bins("cs.bat") then
    return "cs.bat"
  elseif util.has_bins("cs") then
    return "cs"
  elseif util.has_bins("coursier") then
    return "coursier"
  else
    return nil
  end
end
```
to:
```
local function check_for_coursier()
  -- this must be first the second "cs" is also found as binary but we should
  -- be more specific on Windows
  if util.is_windows and util.has_bins("cs.bat") then
    return "cs.bat"
  elseif util.has_bins("coursier") then
    return "coursier"
  elseif util.has_bins("cs") then
    return "cs"
  else
    return nil
  end
end
```
The problem solved.

### Potential ways to implement

Maybe we can check `coursier` when `cs` doesn't work?

**Comment by ckipp01** [comment]
Hey @chms7 another option that you might consider is to just use `useGlobalExecutable`.

https://github.com/scalameta/nvim-metals/blob/0b9c5303b7402ae24971ed2f0e5890fd72505532/doc/metals.txt#L471-L480

If you set this to `true` you'd then just be able to use `coursier install metals` locally and `nvim-metals` would just use that.

**Comment by chms7** [comment]
OK I got it. Thanks for reply. :)
