### ISSUE TITLE
Better message for 'null'-response from `metals/treeViewReveal` 

### ISSUE THREAD

**Issue by susliko** [scalameta/nvim-metals#546]
### Describe the feature

When `metals/treeViewReveal` responds with `null`, nvim-metals [logs](https://github.com/scalameta/nvim-metals/blob/0b9c5303b7402ae24971ed2f0e5890fd72505532/lua/metals/tvp/init.lua#L473) the following message: "You recieved a node for a view nvim-metals doesn't support"

I'd expect a message which either encourages to open an issue in Metal (is it a case, when we should report to Metals?) or clarifies the impossibility of this action due to Metals lacking some information

Reproduction steps:
- in a scala 3 project open `scala.quoted.Quotes`
- invoke `lua require('metals.tvp').reveal_in_tree()<CR>`
- look at lsp.trace.json
```
[Trace - 00:23:28 AM] Received request 'metals/treeViewReveal - (9)'
Params: {
  "textDocument": {
    "uri": "file:///..../.metals/readonly/dependencies/scala3-library_3-3.2.2-sources.jar/scala/quoted/Quotes.scala"
  },
  "position": {
    "line": 24,
    "character": 35
  }
}


[Trace - 00:23:28 AM] Sending response 'metals/treeViewReveal - (9)'. Processing request took 90ms
Result: null
```

**Comment by ckipp01** [comment]
Hey @susliko, thanks for creating this! Yes, I think we can do better here. I have a feeling I didn't even think of this because it was created before Scala 3, so I never experienced the null response (it happens here because there is no Scala 3 support for the tree view).
