### ISSUE TITLE
Better "Restart X" command names

### ISSUE THREAD

**Issue by susliko** [scalameta/nvim-metals#551]
### Describe the feature

Caught myself always pausing on this step whenever I want to restart either Metals or build server. "Restart Server" means the restart of Metals, but build server is also a server :)

<img width="719" alt="image" src="https://user-images.githubusercontent.com/15569000/234231297-e4dacff2-8620-4faf-8abf-e15614a2379b.png">

### Potential ways to implement

Probably, command names like
"Restart Build Server" and "Restart LSP Server", or
"Restart Build" and "Restart Metals" might help to disambiguate

**Comment by ckipp01** [comment]
ah yea these could be better. They were originally mimicking what the actual commands in Metals were, which aren't really clear. Feel free to PR a change to make these clearer.

**Comment by ckipp01** [comment]
Closed via #552
