### ISSUE TITLE
Nvim hangs on quit when metals is enabled

### ISSUE THREAD

**Issue by sbushmanov** [scalameta/nvim-metals#565]
Nvim hangs on quitting `:q, :qa, :q!, :exit` when nvim-metals is enabled.

The cursor is moved to the first column of the command line and stays there forever.
Quitting freezed session is only possible via killing terminal.
This does happen in several terminals I tried (alacritty, lxterminal)
When metals is disabled the problem goes away.
Disabling dap brings no relief. When I'm in scala project, it doesn't matter if I'm closing a scala or any other buffer (e.g. text). The result is always freeze
And it doesn't happen in  other languages like python where LSP is also enabled.

My metals config is the same as suggested [here](https://github.com/scalameta/nvim-metals/discussions/39)

The problem came after recent nvim/plugins update.

OS: Ubuntu 22.04
NVIM v0.10.0-dev (latest nightly, updated via apt)
metals: v0.11.9 (latest, updated via Packer)

Rolling NVIM back to NVIM v0.9.1-dev-88+g6f7e5ce00 somehow resolved the problem.

Any help in resolving/debugging the issue with nvim v10 is appreciated!

**Comment by ckipp01** [comment]
Hey @sbushmanov, it's really hard to diagnose without an exact reproduction or knowing your exact setup. It's unlikely that this is nvim-metals doesn't something directly, but some odd interaction maybe with another plugin. I'd recommend trying to verify this with a bare nvim and _only_ nvim-metals installed. See if you have the behavior then with no other plugins. Then try to slowly add things in and see what might be conflicting/causing issues.

**Comment by ckipp01** [comment]
Since I haven't heard back in a month I'm going to go ahead and close. If you tried to minimize with what I mentioned up above and you're still having this issue, please do report back.
