### ISSUE TITLE
Possible bug: Getting recursive project/project/... files

### ISSUE THREAD

**Issue by lervag** [scalameta/nvim-metals#571]
### Describe the bug

After loading a project with nvim-metals I notice I get the file `project/metals.sbt`. But I also get `project/project/metals.sbt`. My project has the following structure:

```
.
├── build.sbt
├── components  <- code
├── logs
│   └── log.json
├── modules <- code
├── project
│   ├── build.properties
│   ├── metals.sbt <- generated by nvim-metals
│   ├── plugins.sbt
│   ├── project <- generated by nvim-metals
│   └── target <- generated by nvim-metals
```

The extra `project` directory looks something like this:

```
project
├── project
│   ├── metals.sbt
│   ├── project
│   │   ├── metals.sbt
│   │   ├── project
│   │   │   └── target
│   │   │       └── config-classes
│   │   └── target
│   │       ├── config-classes (fewer files)
│   │       ├── scala-2.12 (some files)
│   │       └── streams (some files)
│   └── target
│       ├── config-classes (many files)
│       ├── scala-2.12 (many files)
│       └── streams (many files)
└── target
    ├── config-classes (most files)
    ├── scala-2.12 (most files)
    └── streams (most files)
```

To reproduce, you would need my code - but I can't share that. However, the steps are something like this:
* Start from a clean version of the code.
* Open a Scala file.
* When Metals ask to import the build, I say yes.
* Metals works in the background indexing and compiling.
* When it is finished, the above mentioned files are created.

I wouldn't really know where to begin looking in to this, but I hope someone might be able to help figure it out.

My related configuration:
* https://github.com/lervag/dotnvim/blob/86d5b9bc042f7b3248f2862c3fd0b2815969a0d7/plugin/lsp.lua#L348-L431

### Expected behavior

I would assume that only the single file `metals.sbt` was generated inside the `project` folder:

```
.
├── project
│   ├── build.properties
│   ├── metals.sbt <- generated by nvim-metals
│   ├── plugins.sbt
```

### Operating system

Linux

### Version of Metals

v0.11.12

### Commit of nvim-metals

51cd9fabe8ba7ff9abafd0c1ec4292f3a2eb1a31

**Comment by ckipp01** [comment]
Hey @lervag, good question! So this is actually the expected behavior. You'll actually see it reflected in the doctor even when you look at your build targets. You'll notice you'll have a `<something>-build` and `<something>-build-build`. The reason for this is that Metals needs to support editing your build file. So in order to support your root `build.sbt` file it creates the first `project/metals.sbt` file. Then Metals also needs to support editing in your meta-build, aka anything in your `project/*`. So in order to do that it needs to add the plugin one layer up in `project/project/metals.sbt`. It will essentially keep going one layer up to ensure you have editor support in the layer below. Not the prettiest, but it's how it works :).

**Comment by lervag** [comment]
> Hey @lervag, good question! So this is actually the expected behavior. …

Thank you for the good explanation! So, if I understand correctly, I would want to add `project/project` to my `.gitignore` file, as well as `.metals` and `metals.sbt`, right?

**Comment by ckipp01** [comment]
> > Hey @lervag, good question! So this is actually the expected behavior. …
> 
> Thank you for the good explanation! So, if I understand correctly, I would want to add `project/project` to my `.gitignore` file, as well as `.metals` and `metals.sbt`, right?

You don't need to add the full `project/project`. As long as you have the normal things like `target` in your `.gitignore`, just adding the following should be all you need for Metals related projects

```
.bsp/
.bloop/
.metals/
metals.sbt
```

**Comment by lervag** [comment]
Ah, yes, of course. You're right!
