### ISSUE TITLE
Import build window is not dismissed from the UI

### ISSUE THREAD

**Issue by ghostbuster91** [scalameta/nvim-metals#589]
### Describe the bug

Sometimes when I am switching branches or doing something that is causing the need to reimport project my neovim looses focus from the "Import build" window. After switching to a different file the window disappears, so it seems that it is a fault of UI which is not updated. 

![Screenshot from 2023-07-14 11-48-29](https://github.com/scalameta/nvim-metals/assets/5662622/aa21b12a-05b6-4385-bce6-4f7c572b8632)

### Expected behavior

UI should be updated and the window should vanish. 

### Operating system

Linux

### Version of Metals

0.11.12

### Commit of nvim-metals

cd50bfeae9915b827289141ee9914b79fc8887aa

**Comment by ckipp01** [comment]
Thanks for the report @ghostbuster91 although this isn't something that `nvim-metals` is actually in control of at all, so this would need to be reported upstream. In this scenario this request is the `window/showMessageRequest` which Nevom handles [here](https://github.com/neovim/neovim/blob/2ecba65b4ba741618ecbfd2a50a939987078bc98/runtime/lua/vim/lsp/handlers.lua#L72-L106) and it uses `vim.ui.select` under the hood. So this behavior would need to be addressed either in Neovim or whatever you're using to implement `vim.ui.select`.

**Comment by ghostbuster91** [comment]
Good to know, thanks for the explanation!
