### ISSUE TITLE
False negative warning about not-installed Metals

### ISSUE THREAD

**Issue by chuwy** [scalameta/nvim-metals#590]
### Describe the bug

1. Having a freshly installed sbt, nvim and metals (all through Nix)
1. Open any scala file or `build.sbt`
2. See a warning that Metals not installed and advice to run `:MetalsInstall`
3. Yet all functionality such as go-to-definition works as expected

```
$ metals --version

metals 0.11.12

# Note:
#   Supported Scala versions:
#     Scala 3: 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.3.0-RC3, 3.3.0-RC4
...
```

* sbt - 1.9.1
* Scala - 3.3.0
* `:MetalsRunDoctor` show all green
* `:MetalsToggleLogs` shows an empty buffer

---

After I ran `:MetalsInstall` - it shows something in logs, but every time I start vim - it tells me `Client 1 quit with exit code 1 and signal 0`

### Expected behavior

No warnings.

### Operating system

macOS

### Version of Metals

v0.11.12

### Commit of nvim-metals

cd50bfeae9915b827289141ee9914b79fc8887aa

**Comment by ckipp01** [comment]
Hey @chuwy, thanks for the report. If you're using Nix and not letting `nvim-metals` handle the installation are you making sure to set https://github.com/scalameta/nvim-metals/blob/cd50bfeae9915b827289141ee9914b79fc8887aa/doc/metals.txt#L482 to true?

**Comment by ckipp01** [comment]
I haven't heard back about this at all, so I'm assuming this has been figured out. If this isn't the case, please do report back.
