### ISSUE TITLE
Issues getting this to work with lazy

### ISSUE THREAD

**Issue by TimWSpence** [scalameta/nvim-metals#592]
### Describe the bug

Sorry, I don't have a very clear problem to report. I've just really struggled to get metals and neovim to work. I'd say jump to definition works ~25% of the time on any repo. Diagnostics (compiler warnings/errors) occasionally appear as an overlay but then often don't disappear again (after the problem is fixed) without killing the buffer. Import suggestions do seem to work a bit more reliably. Both metals 1.0 and recent previous versions exhibit the same behaviour.

The fact that it works sometimes makes me think that my setup isn't completely wrong but I've bashed my head against it for a long time and have no idea what is wrong so any help would be massively appreciated.

I've extracted and uploaded my nvim config [here](https://github.com/TImWSpence/nvim). In particular the Scala config is in `lua/plugins/scala.lua`. Other lsp-config is in `lua/plugins/lang.lua` in case there's any weird interaction there.

I do always see a huge number of
```
Jul 20, 2023 3:40:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 178
```
messages in the metals logs. I'm not sure if this is relevant or not.

I should also say that I have the same experience on two separate machines. Thanks so much in advance! If there's any other info I can provide then let me know.

### Operating system

macOS

### Version of Metals

v1.0.0

### Commit of nvim-metals

92e2085f08da4598c6ae0c19c332c5c04b33a2c5

**Comment by ckipp01** [comment]
Hey @TimWSpence, I'm sorry it hasn't been working great for you. Let's try to figure out what's going on. I'm not super familiar with Lazy, so I'm not real sure on the inner-workings of how it works with other plugins. Taking a look at the files you linked:

## `scala.lua`

- I see in https://github.com/TimWSpence/nvim/blob/dc271e3385e425746c0854b53ff4c2e1224c9143/lua/plugins/scala.lua#L5 you have a `BufEnter` trigger only for worksheets. Is this intended?

## `lang.lua`

- The one thing that sticks out to me here is https://github.com/TimWSpence/nvim/blob/dc271e3385e425746c0854b53ff4c2e1224c9143/lua/plugins/lang.lua#L12. What exactly does ensure installed mean? There's a chance that this could be causing issues since `nvim-metals` actually fully handles the installation of metals. If you don't want it to, then you'll want to make sure to use `useGlobalExecutable` [here](https://github.com/scalameta/nvim-metals/blob/92e2085f08da4598c6ae0c19c332c5c04b33a2c5/doc/metals.txt#L482-L491) to tell it to look for a `metals` that is available.

**Comment by TimWSpence** [comment]
Thanks so much @ckipp01!

The `BufEnter` was just a hack because worksheet files don't seem to be classified as Scala according to Lazy's filetype. But removing that makes no difference.

That bit in `lang.lua` is just installing the treesitter grammar for scala rather than any LSP stuff (unless my understanding is wildly wrong 😅 )

But I've just tried removing all the files in `plugin` other than `scala.lua` to get a pretty vanilla Lazyvim setup and it still sees enormous numbers of timeouts in the metals logs and not much works 😭 Do you have a known good complete nvim setup with metals that I could try just as a comparison?

**Comment by TimWSpence** [comment]
Hey @ckipp01, I think I've found at least one issue (although have no idea how to fix it 😅 ). If I open a file (`nvim <path>`) then metals starts up and attaches successfully and seems generally happy. However, if I then open another file (either directly or via jump-to-definition) then the new buffer is not attached to the LSP client. If I run `:lua vim.lsp.buf_attach_client(0,1)` in the new buffer then metals starts to work in that one too, but still doesn't work in any future buffers.

Checking `Lazy` I see that nvim-metals is still loaded so I don't _think_ it's due to Lazy but I definitely could be wrong about that. And I have no clue how to debug the depths of nvim-metals and lsp-config to figure out why it doesn't attach 😅

**Comment by TimWSpence** [comment]
Actually I think my understanding of neovim plugin loading and Lazy was wrong 🤦 I thought that the Lazy config would be evaluated per buffer but actually it's only evaluated once when the plugin is loaded. Comparing to [rust-tools](https://github.com/simrat39/rust-tools.nvim/blob/0cc8adab23117783a0292a0c8a2fbed1005dc645/lua/rust-tools/lsp.lua#L19) which I configured similarly, it works because it sets up that autocmd to attach any new buffers. So if I want to keep the Lazy plugin loading then I need to setup a similar autocmd.

I'll let you know how I get on 😆

**Comment by TimWSpence** [comment]
OK that was the problem. It looks like it's working much better now. Apologies for wasting your time on my stupidity 😅

**Comment by ckipp01** [comment]
Hey! Ha, no worries at all and nice debugging. I should have also thought of that as I believe this has bit a couple people before as well. I'll go ahead and close now, but if you still have issues with something not working as expected, please do report back. Actually if you wouldn't mind pasting your new config in here in case someone else stumbles on this it might help.

**Comment by TimWSpence** [comment]
> Hey! Ha, no worries at all and nice debugging. I should have also thought of that as I believe this has bit a couple people before as well. I'll go ahead and close now, but if you still have issues with something not working as expected, please do report back. Actually if you wouldn't mind pasting your new config in here in case someone else stumbles on this it might help.

Thanks again! Thus far it's working really nicely :) I see you already changed the title to something more helpful mentioning Lazy 😆 Here's my config now (it was a very small change to fix it):

```lua
return {
  "scalameta/nvim-metals",
  dependencies = { "nvim-lua/plenary.nvim", "mfussenegger/nvim-dap" },
  ft = { "scala", "sbt" },
  event = "BufEnter *.worksheet.sc",
  config = function()
    local api = vim.api
    ----------------------------------
    -- OPTIONS -----------------------
    ----------------------------------
    -- global
    vim.opt_global.completeopt = { "menuone", "noinsert", "noselect" }
    vim.opt_global.shortmess:remove("F")
    vim.opt_global.shortmess:append("c")
    -- LSP Setup ---------------------
    ----------------------------------
    local metals_config = require("metals").bare_config()

    -- Example of settings
    metals_config.settings = {
      showImplicitArguments = true,
      showInferredType = true,
      superMethodLensesEnabled = true,
      showImplicitConversionsAndClasses = true,
    }

    -- *READ THIS*
    -- I *highly* recommend setting statusBarProvider to true, however if you do,
    -- you *have* to have a setting to display this in your statusline or else
    -- you'll not see any messages from metals. There is more info in the help
    -- docs about this
    metals_config.init_options.statusBarProvider = "on"

    -- Example if you are using cmp how to make sure the correct capabilities for snippets are set
    metals_config.capabilities = require("cmp_nvim_lsp").default_capabilities()

    -- Debug settings if you're using nvim-dap
    local dap = require("dap")

    dap.configurations.scala = {
      {
        type = "scala",
        request = "launch",
        name = "RunOrTest",
        metals = {
          runType = "runOrTestFile",
          --args = { "firstArg", "secondArg", "thirdArg" }, -- here just as an example
        },
      },
      {
        type = "scala",
        request = "launch",
        name = "Test Target",
        metals = {
          runType = "testTarget",
        },
      },
    }

    metals_config.on_attach = function(client, bufnr)
      local metals = require("metals")
      metals.setup_dap()

      local wk = require("which-key")
      wk.register({
        ["<localleader>"] = {
          h = {
            name = "hover",
            c = {
              function()
                metals.toggle_setting("showImplicitConversionsAndClasses")
              end,
              "Toggle show implicit conversions and classes",
            },
            i = {
              function()
                metals.toggle_setting("showImplicitArguments")
              end,
              "Toggle show implicit arguments",
            },
            t = {
              function()
                metals.toggle_setting("showInferredType")
              end,
              "Toggle show inferred type",
            },
          },
          t = {
            name = "Tree view",
            t = {
              function()
                require("metals.tvp").toggle_tree_view()
              end,
              "Toggle tree view",
            },
            r = {
              function()
                require("metals.tvp").reveal_in_tree()
              end,
              "Review in tree view",
            },
          },
          w = {
            function()
              metals.hover_worksheet({ border = "single" })
            end,
            "Hover worksheet",
          },
        },
      }, {
        buffer = bufnr,
      })
      wk.register({
        ["<localleader>t"] = {
          function()
            metals.type_of_range()
          end,
          "Type of range",
        },
      }, {
        mode = "v",
        buffer = bufnr,
      })
    end

    local nvim_metals_group = vim.api.nvim_create_augroup("nvim-metals", { clear = true })
    vim.api.nvim_create_autocmd("FileType", {
      -- NOTE: You may or may not want java included here. You will need it if you
      -- want basic Java support but it may also conflict if you are using
      -- something like nvim-jdtls which also works on a java filetype autocmd.
      pattern = { "scala", "sbt", "java" },
      callback = function()
        require("metals").initialize_or_attach(metals_config)
      end,
      group = nvim_metals_group,
    })
  end,
}
```

**Comment by madtrick** [comment]
@TimWSpence did you also solve the never ending `handleCancellation` issue?

```
Jul 20, 2023 3:40:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 178
```

In my case it gets printed for every keystroke in a scala file.

**Comment by TimWSpence** [comment]
@madtrick oh dear, that's a lot 😅 Is it working apart from that?

I do still get those messages but not that kind of volume of them
