### ISSUE TITLE
fzf-lua extension

### ISSUE THREAD

**Issue by ornicar** [scalameta/nvim-metals#701]
### Describe the feature

LazyVim has now [replaced telescope with fzf-lua](https://www.lazyvim.org/news#added-plugins) by default.

The metals telescope extension is very, very handy, but is no longer compatible with LazyVim. It would be fantastic to have a [fzf-lua](https://github.com/ibhagwan/fzf-lua/wiki/Advanced#fzf-exec-api) flavour of it.

### Potential ways to implement

I'm giving it a try. No promise of results.

**Comment by ornicar** [comment]
https://github.com/scalameta/nvim-metals/pull/702

**Comment by ckipp01** [comment]
Since this was closed I'll go ahead and close this.
