### ISSUE TITLE
MetalsLogsToggle is confused if another terminal is open

### ISSUE THREAD

**Issue by keynmol** [scalameta/nvim-metals#87]
When you have an integrated terminal open in nvim, running MetalsLogsToggle will say that logs are already opened.

**To Reproduce** Steps to reproduce the behavior:

1. Open any metals project
2. Open an integrated terminal
3. Run :MetalsLogsToggle

**Expected behavior**

A terminal is opened tailing metals logs

**Actual behavior**

Command things logs are already opened

**Installation:**

- Operating system: Linux
- Nvim version: v0.5.0-dev+1012-gfe1ebea33
- Commit of nvim-metals: 13635adae2d4a64d41d48ed8587ee022825e2e17
- Metals version: 0.9.10

**Search terms**

metals, logs, terminal, nvim, toggle

**Comment by ckipp01** [comment]
Thanks for the report @keynmol! This should totally be fixable. I do a pretty naive check here:  https://github.com/scalameta/nvim-metals/blob/bcb5600bef764b6f43e9809469343a1a5d6779e5/lua/metals.lua#L130-L141

I should be able to easily look at the name and do a finer grained check.

**Comment by keynmol** [comment]
If you don't mind, I'll give a go at fixing it (I think I have all the API calls from nvim, just need to brush up on Lua)

**Comment by ckipp01** [comment]
> If you don't mind, I'll give a go at fixing it (I think I have all the API calls from nvim, just need to brush up on Lua)

For sure!
