### ISSUE TITLE
Busted tests

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#9]
**Task**

I know next to nothing about Lua testing, but the recent `root_pattern` function that was added is a prime suspect to be tested to ensure that the workspaces are actually being correctly set with nested build files. This seems to be working fine when testing manually, but it'd be nice to test this to ensure it.

**Additional context**

- I think busted seems likes a good choice to use.
- It looks like it looks in `src` for modules when testing, so I need to figure out how to get it to instead look in the `lua` directory, which is more common in nvim plugins. There is a `-m` flag that should work for this
- `vim` will be undefined when running the test, so I'm not sure how to get around that

Look for nvim plugins that are tested first.

**Search terms**
tests, busted

EDIT: Relevant comment from @tjdevries on gitter:

> You need to run the test through neovims Lua runtime basically. It's a little difficult to set up in some ways.

**Comment by tjdevries** [comment]
I'd love it if you tried it out with my plugin I've been working on here: https://github.com/tjdevries/plenary.nvim

You can use the test harness and the instructions I have for busted to run the tests. It will solve your problem number 3, since it runs from within an nvim instance.

Feedback definitely welcome (right now it works pretty well for my purposes)

**Comment by ckipp01** [comment]
Whoa, This is awesome! Thanks for recommending this! I'll definitely give this a try and report back!

**Comment by tjdevries** [comment]
Great :) if nvim loads the plugin, then it should be as simple as calling the functions I describe in the readme.

Feel free to reach out to me on gitter to ask questions if that's easier.

**Comment by ckipp01** [comment]
Going to go ahead and close this. We've started to slowly add these in a while ago.
